### ISSUE TITLE
Revoke-MgUserSign cmdlet

### ISSUE THREAD

**Issue by lsimon17** [microsoftgraph/msgraph-sdk-powershell#1359]
I am attempting to migrate our offboarding script from the AzureAD commands to the Graph commands and am trying to revoke user sessions. When I attempt to run the following command(s): 
```
$UserID = (Get-MgUser -UserID $OffboardedUserEmail).Id
Revoke-MgUserSign -UserId $userID -Debug
```
I get hit with the following error:
```
DEBUG: [CmdletBeginProcessing]: - Revoke-MgUserSign begin processing with parameterSet 'Revoke1'.
DEBUG: [Authentication]: - AuthType: 'Delegated', AuthProviderType: 'InteractiveAuthenticationProvider', ContextScope: 'CurrentUser', AppName: 'Microsoft Graph PowerShell'.
DEBUG: [Authentication]: - Scopes: [Group.ReadWrite.All, openid, Organization.Read.All, profile, User.Read, User.Read.All, User.ReadWrite.All, email].
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://graph.microsoft.com/v1.0/users/userid/microsoft.graph.revokeSignInSessions

Headers:


Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : 5b729035-2f30-490b-8d15-a825277d1f8e
client-request-id             : 5b729035-2f30-490b-8d15-a825277d1f8e
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"Canada East","Slice":"E","Ring":"2","ScaleUnit":"002","RoleInstance":"QB1PEPF00001E92"}}
x-ms-resource-unit            : 1
OData-Version                 : 4.0
Cache-Control                 : no-cache
Date                          : Thu, 30 Jun 2022 12:46:03 GMT
Location                      : https://graph.microsoft.com/

Body:
{
  "@odata.context": "https://graph.microsoft.com/v1.0/$metadata#Edm.Boolean",
  "value": true
}


DEBUG: [CmdletException]: Received exception with message 'NullReferenceException - Object reference not set to an instance of an object. :    at Microsoft.Graph.PowerShell.Cmdlets.RevokeMgUserSign_Revoke1.<onOk>d__53.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.UsersActions.<UsersRevokeSignInSessions1_Call>d__1319.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Graph.PowerShell.UsersActions.<UsersRevokeSignInSessions1_Call>d__1319.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.UsersActions.<UsersRevokeSignInSessions1>d__1317.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Cmdlets.RevokeMgUserSign_Revoke1.<ProcessRecordAsync>d__49.MoveNext()'
Revoke-MgUserSign : Object reference not set to an instance of an object.
At line:23 char:1
+ Revoke-MgUserSign -UserId $userID -Debug
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Revoke-MgUserSign_Revoke1], NullReferenceException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.RevokeMgUserSign_Revoke1
 
DEBUG: [CmdletEndProcessing]: - Revoke-MgUserSign end processing.
```

I understand there is a workaround with using: 
`Invoke-MgGraphRequest -Method POST -Uri "[https://graph.microsoft.com/v1.0/users/{id}/microsoft.graph.revokeSignInSessions]`
but I'd like to use the modules only if possible

**Comment by lsimon17** [comment]
@peombwa thank you for the quick response. That resolved the issue for me!
