### ISSUE TITLE
Unable to update UserPrincipalName

### ISSUE THREAD

**Issue by TomAguero** [microsoftgraph/msgraph-sdk-powershell#1560]
I'm converting old scripts to MS Graph and am running into an issue updating user principal names, We have 28 email domains which people occasionally move through and of course marriages/divorces/HR typos.

I used to use
````
Set-MsolUserPrincipalName -UserPrincipalName $OldPSMTP -NewUserPrincipalName $NewPSMTP
````
The documentation on Update-MGUser isn't awesome so I'm not exactly sure how to do this, I've tried
````
Update-MGUser -UserId $OldPSMTP -UserPrincipalName $NewPSMTP
````
And
````
$Params = @{
    UserPrincipalName = $newPSMTP
}
Update-MGUser -UserId $OldPSMTP -BodyParameter $params
````
Both result in the same error
````
Update-MGUser : One or more errors occurred.
At line:1 char:1
+ Update-MGUser -UserId $OldPSMTP -UserPrincipalName $NewPSMTP
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-MgUser_UpdateExpanded1], AggregateException
    + FullyQualifiedErrorId : System.AggregateException,Microsoft.Graph.PowerShell.Cmdlets.UpdateMgUser_UpdateExpanded1
````
Which when I do $_.Exception.ToString() | out-host becomes
````
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Graph.Authentication.Core, Version=1.12.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.Graph.PowerShell.Module.<OnCmdletBeginProcessing>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Graph.PowerShell.Module.OnCmdletBeginProcessing(String id, CancellationToken cancellationToken, Func`1 getEventData, Func`4 signal, InvocationInfo invocationInfo)
   at Microsoft.Graph.PowerShell.Module.<EventHandler>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Module.<Signal>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Cmdlets.UpdateMgUser_Update.<Microsoft-Graph-PowerShell-Runtime-IEventListener-Signal>d__55.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Graph.PowerShell.Cmdlets.UpdateMgUser_Update.BeginProcessing()
   at System.Management.Automation.Cmdlet.DoBeginProcessing()
   at System.Management.Automation.CommandProcessorBase.DoBegin()
---> (Inner Exception #0) System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Graph.Authentication.Core, Version=1.12.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Graph.Authentication.Core, Version=1.12.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.Graph.PowerShell.Module.<OnCmdletBeginProcessing>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Graph.PowerShell.Module.OnCmdletBeginProcessing(String id, CancellationToken cancellationToken, Func`1 getEventData, Func`4 signal, InvocationInfo invocationInfo)
   at Microsoft.Graph.PowerShell.Module.<EventHandler>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Module.<Signal>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Cmdlets.UpdateMgUser_Update.<Microsoft-Graph-PowerShell-Runtime-IEventListener-Signal>d__55.MoveNext()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
<---
````
I had the 1.12.3 version installed, but forced the install of 1.12.2 and removed the 1.12.3 module from my active session
````
Get-Module Microsoft.Graph.Authentication 

ModuleType Version    Name                                ExportedCommands                                                                                             
---------- -------    ----                                ----------------                                                                                             
Script     1.12.2     Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGraph, Disconnect-MgGraph, Get-MgContext...}   
````
But I still get the same error. Any ideas or any further troubleshooting I should do?

**Comment by peombwa** [comment]
I'm able to update a user's UPN just fine using the latest version of the module:
![image](https://user-images.githubusercontent.com/7061532/194648941-ca27224a-523e-4096-ac9a-c12caf2a9bef.png)

The error message `Could not load file or assembly 'Microsoft.Graph.Authentication.Core, Version=1.12.2.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies` suggests that the imported versions of `Microsoft.Graph.Users` and `Microsoft.Graph.Authentication` are not the same. Use `Get-Module Microsoft.Graph.Users, Microsoft.Graph.Authentication` to verify this.

Please ensure you are using the latest version of the module (`v1.12.3`) by running `Update-Module Microsoft.Graph`. Is there are reason you are not using version 1.12.3?

**Comment by TomAguero** [comment]
Sorry, COVID finally caught up with me. I think this was an issue with PowerShell 5.1 as it worked fine in 7.2 which I really should've been using already anyway
