### ISSUE TITLE
Potential ThreadSafe issue

### ISSUE THREAD

**Issue by MarkDordoy** [microsoftgraph/msgraph-sdk-powershell#1601]
I run some powershell that interacts with MS graph in parallel processes (using the built in pwsh foreach-object -parallel workflow). 

I was using module version 1.9.3 without issue. I attempted to update to 1.14.0 and I started getting errors as shown below:

```
DEBUG: [CmdletEndProcessing]: - Get-MgGroupMember end processing.
DEBUG: [CmdletEndProcessing]: - Get-MgGroupMember end processing.
DEBUG: [CmdletBeginProcessing]: - Get-MgGroupMember begin processing with parameterSet 'List1'.
DEBUG: [Authentication]: - AuthType: 'AppOnly', AuthProviderType: 'ClientCredentialProvider', ContextScope: 'Process', AppName: 'mdordoy-dev-app '.
DEBUG: [Authentication]: - Scopes: [Group.Read.All, EntitlementManagement.Read.All, User.Read.All, GroupMember.Read.All].
DEBUG: [CmdletException]: Received exception with message 'InvalidOperationException - Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct. :    at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Net.Http.Headers.HttpHeaders.TryGetAndParseHeaderInfo(HeaderDescriptor key, HeaderStoreItemInfo& info)
   at Microsoft.Graph.PowerShell.Authentication.Helpers.HttpHelpers.GetGraphHttpClient(InvocationInfo invocationInfo, IAuthContext authContext)
   at Microsoft.Graph.PowerShell.Module.BeforeCreatePipeline(InvocationInfo invocationInfo, HttpPipeline& pipeline)
   at Microsoft.Graph.PowerShell.Module.CreatePipeline(InvocationInfo invocationInfo, String parameterSetName)
   at Microsoft.Graph.PowerShell.Cmdlets.GetMgGroupMember_List1.ProcessRecordAsync()'
DEBUG: [CmdletBeginProcessing]: - Get-MgGroupMember begin processing with parameterSet 'List1'.
DEBUG: [Authentication]: - AuthType: 'AppOnly', AuthProviderType: 'ClientCredentialProvider', ContextScope: 'Process', AppName: 'mdordoy-dev-app '.
DEBUG: [Authentication]: - Scopes: [Group.Read.All, EntitlementManagement.Read.All, User.Read.All, GroupMember.Read.All].
DEBUG: [CmdletException]: Received exception with message 'InvalidOperationException - Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct. :    at System.Collections.Generic.Dictionary`2.FindValue(TKey key)
   at System.Net.Http.Headers.HttpHeaders.TryGetAndParseHeaderInfo(HeaderDescriptor key, HeaderStoreItemInfo& info)
   at Microsoft.Graph.PowerShell.Authentication.Helpers.HttpHelpers.GetGraphHttpClient(InvocationInfo invocationInfo, IAuthContext authContext)
   at Microsoft.Graph.PowerShell.Module.BeforeCreatePipeline(InvocationInfo invocationInfo, HttpPipeline& pipeline)
   at Microsoft.Graph.PowerShell.Module.CreatePipeline(InvocationInfo invocationInfo, String parameterSetName)
   at Microsoft.Graph.PowerShell.Cmdlets.GetMgGroupMember_List1.ProcessRecordAsync()'
```

If i run the script slower, will less threads processing at one, i have this happen much less. If I throttle at 1 thread at a time, the issue goes away.

**Comment by MarkDordoy** [comment]
I believe this bug was introduced before version 1.14.0 as i also see it with version 1.11.x. Ive not tested others, but it's likely it existed for some time.

**Comment by MarkDordoy** [comment]
my workaround for this is to use Invoke-MgGraphRequest to get group members and this seems to be ok.

**Comment by peombwa** [comment]
Thanks for following up on this.

Can please share a script that we can use to reproduce the error? Also, please share with us the output of `$Error[0].Exception` immediately after the exception occurs.

**Comment by peombwa** [comment]
I've been able to reproduce the bug using:
``` powershell
1..1000 | ForEach-Object -Parallel {
    Import-Module Microsoft.Graph.Groups -RequiredVersion 1.13.0
    Connect-MgGraph | out-null
    Get-MgGroupMemberByRef -GroupId "016828b9-44e2-4061-a5f9-3fc531284a5d"
}
```

``` powershell
➜ $Error[0].Exception

Message        : An item with the same key has already been added. Key: System.Net.Http.Headers.HeaderDescriptor
ParamName      :
TargetSite     : Void ThrowAddingDuplicateWithKeyArgumentException[T](T)
Data           : {}
InnerException :
HelpLink       :
Source         : System.Private.CoreLib
HResult        : -2147024809
StackTrace     :    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
                    at Microsoft.Graph.PowerShell.Authentication.Helpers.HttpHelpers.GetGraphHttpClient(InvocationInfo
                 invocationInfo, IAuthContext authContext)
                    at Microsoft.Graph.PowerShell.Module.BeforeCreatePipeline(InvocationInfo invocationInfo, HttpPipeline& pipeline)
                    at Microsoft.Graph.PowerShell.Module.CreatePipeline(InvocationInfo invocationInfo, String parameterSetName)
                    at Microsoft.Graph.PowerShell.Cmdlets.GetMgGroupMemberByRef_List1.ProcessRecordAsync()
```

You are right, the issue has been present for some time. We will issue a bug fix in the next release.
