### ISSUE TITLE
New-MgDirectoryAdministrativeUnitMemberByRef_Create: An item with the same key has already been added. Key: @odata.id

### ISSUE THREAD

**Issue by tpjl** [microsoftgraph/msgraph-sdk-powershell#1613]
Adding members to administrative units no longer appears to work. 
Checking audit log, the same script successfully added a member to an administrative unit 2022-10-21. Possible it has worked since and there just hasn't been any need for the script. Today (2022-11-02) it gets the error message below. 

Powershell 7
Module version 1.13.0 and 1.14.0 both tested
Both app and delegated authentication tested
Both beta and v1.0 tested

```powershell
Connect-MgGraph
New-MgDirectoryAdministrativeUnitMemberByRef -AdministrativeUnitId $AdminUnitObjectId -BodyParameter @{"@odata.id"="https://graph.microsoft.com/beta/users/$userObjectId"}


New-MgDirectoryAdministrativeUnitMemberByRef_Create: An item with the same key has already been added. Key: @odata.id
```

**Comment by fblix** [comment]
got the same issue with "New-MgApplicationOwnerByRef"

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

Please share the output of following to help us reproduce the issues:
- Debug output of `New-MgDirectoryAdministrativeUnitMemberByRef -AdministrativeUnitId $AdminUnitObjectId -BodyParameter @{"@odata.id"="https://graph.microsoft.com/beta/users/$userObjectId"} -Debug`.
- `$PSVersionTable`.

**Comment by tpjl** [comment]
Thoroughly confused. With `-debug` switch it works! I tried it again without and it's still broken (error is thrown, user is not added to AU) but with -debug the user gets added to the admin unit.

```powershell
PS C:\> New-MgDirectoryAdministrativeUnitMemberByRef -AdministrativeUnitId $AdminUnitObjectId -BodyParameter @{"@odata.id"="https://graph.microsoft.com/v1.0/users/$userObjectId"} -Debug
DEBUG: [CmdletBeginProcessing]: - New-MgDirectoryAdministrativeUnitMemberByRef begin processing with parameterSet 'Create1'.
DEBUG: [Authentication]: - AuthType: 'AppOnly', AuthProviderType: 'ClientCredentialProvider', ContextScope: 'Process', AppName: 'My App Name'.
DEBUG: [Authentication]: - Scopes: [User.Read.All, GroupMember.Read.All, AdministrativeUnit.ReadWrite.All].

Confirm
Are you sure you want to perform this action?
Performing the operation "New-MgDirectoryAdministrativeUnitMemberByRef_Create1" on target "Call remote 'DirectoryAdministrativeUnitsCreateMembersGraphBPreRef1' operation".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): y
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://graph.microsoft.com/v1.0/directory/administrativeUnits/<My AdminUnits Object Id>/members/$ref

Headers:
SdkVersion                    : graph-powershell/1.14.0,Graph-dotnet-1.25.1
FeatureFlag                   : 00000047
Cache-Control                 : no-store, no-cache
User-Agent                    : Mozilla/5.0,(Windows NT 10.0; Microsoft Windows 10.0.20348; en-US),PowerShell/7.2.6,New-MgDirectoryAdministrativeUnitMemberByRef_Create1
Accept-Encoding               : gzip

Body:
{
  "@odata.id": "https://graph.microsoft.com/v1.0/users/<My User Object Id>"
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NoContent

Headers:
Cache-Control                 : no-cache
Strict-Transport-Security     : max-age=31536000
request-id                    : 7ba76e71-[...]
client-request-id             : 7ba76e71-[...]
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"West Europe","Slice":"E","Ring":"5","ScaleUnit":"003","RoleInstance":"AM1PEPF000105CC"}}
x-ms-resource-unit            : 1
Date                          : Fri, 04 Nov 2022 08:16:13 GMT

Body:



DEBUG: [CmdletEndProcessing]: - New-MgDirectoryAdministrativeUnitMemberByRef end processing.
PS C:\>
```

```powershell
PS C:\> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

**Comment by tpjl** [comment]
I feel like I'm being gaslit, it now works when run manually from pwsh, even without the -debug switch. Still broken when running from a script. I've added the -debug switch to the script invocation with the following result (run from cmd)
```powershell
C:\>"C:\Program Files\PowerShell\7\pwsh.exe" -File "C:\admin\run.ps1" -ConfigPath "C:\admin\parameters.json"
DEBUG: [CmdletBeginProcessing]: - New-MgDirectoryAdministrativeUnitMemberByRef begin processing with parameterSet 'Create'.
DEBUG: [Authentication]: - AuthType: 'AppOnly', AuthProviderType: 'ClientCredentialProvider', ContextScope: 'Process', AppName: '<My App Name>'.
DEBUG: [Authentication]: - Scopes: [User.Read.All, GroupMember.Read.All, AdministrativeUnit.ReadWrite.All].

Confirm
Are you sure you want to perform this action?
Performing the operation "New-MgDirectoryAdministrativeUnitMemberByRef_Create" on target "Call remote 'DirectoryAdministrativeUnitsCreateMembersGraphBPreRef' operation".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): y
DEBUG: [CmdletException]: Received exception with message 'ArgumentException - An item with the same key has already been added. Key: @odata.id :    at System.Collections.Generic.Dictionary`2.TryInsert(TKey key, TValue value, InsertionBehavior behavior)
   at Microsoft.Graph.PowerShell.Runtime.Json.JsonObject.Add(String name, JsonNode value)
   at Microsoft.Graph.PowerShell.Runtime.Extensions.AddIf[T](T value, String serializedName, Action`2 addMethod)
   at Microsoft.Graph.PowerShell.Models.ReferenceCreate.ToJson(JsonObject container, SerializationMode serializationMode)
   at Microsoft.Graph.PowerShell.IdentityDirectoryManagement.DirectoryAdministrativeUnitsCreateMembersGraphBPreRef(String administrativeUnitId, IReferenceCreate body, Func`2 onNoContent, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.Cmdlets.NewMgDirectoryAdministrativeUnitMemberByRef_Create.ProcessRecordAsync()'
DEBUG: [CmdletException]: Received exception with message 'PipelineStoppedException - The pipeline has been stopped. :    at System.Management.Automation.MshCommandRuntime._WriteErrorSkipAllowCheck(ErrorRecord errorRecord, Nullable`1 actionPreference, Boolean isNativeError)
   at System.Management.Automation.MshCommandRuntime.DoWriteError(Object obj)
   at System.Management.Automation.MshCommandRuntime.WriteError(ErrorRecord errorRecord, Boolean overrideInquire)
   at System.Management.Automation.MshCommandRuntime.WriteError(ErrorRecord errorRecord)
   at Microsoft.Graph.PowerShell.Runtime.PowerShell.AsyncCommandRuntime.WriteError(ErrorRecord errorRecord)
   at System.Management.Automation.Cmdlet.WriteError(ErrorRecord errorRecord)
   at Microsoft.Graph.PowerShell.Cmdlets.NewMgDirectoryAdministrativeUnitMemberByRef_Create.ProcessRecordAsync()
   at Microsoft.Graph.PowerShell.Cmdlets.NewMgDirectoryAdministrativeUnitMemberByRef_Create.ProcessRecordAsync()'

# Output of $userObjectId.GetType()
IsPublic IsSerial Name                                     BaseType
-------- -------- ----                                     --------
True     True     String                                   System.Object
# Output of $userObjectId
ef10c0e0-[...]

# Output of $PSVersionTable
Name                           Value
----                           -----
PSVersion                      7.2.6
PSEdition                      Core
GitCommitId                    7.2.6
OS                             Microsoft Windows 10.0.20348
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

```

**Comment by peombwa** [comment]
Thanks for the `-Debug` log. This looks like an intermittent bug with how we serialize the property in `-BodyParameter` to JSON. I'll investigate to see if I can narrow it down.

As a workaround, you can try using `-OdataId` parameter on `New-MgDirectoryAdministrativeUnitMemberByRef` to add an administrative unit member instead:
``` powershell
New-MgDirectoryAdministrativeUnitMemberByRef -AdministrativeUnitId $AdminUnitObjectId -OdataId "https://graph.microsoft.com/beta/users/$userObjectId"
```
