### ISSUE TITLE
revoke-mgusersign still returns Object reference not set to an instance of an object. 

### ISSUE THREAD

**Issue by Absoblogginlutely** [microsoftgraph/msgraph-sdk-powershell#1676]
See #1241 and #1359 that are both closed but issue still exists.

Attempting to call revoke-mgusersign returns  Object reference not set to an instance of an object

```>revoke-mgusersign -userid (get-mguser -userid $userid).id -debug
DEBUG: [CmdletBeginProcessing]: - Revoke-MgUserSign begin processing with parameterSet 'Revoke'.
DEBUG: [Authentication]: - AuthType: 'AppOnly', AuthProviderType: 'ClientCredentialProvider', ContextScope: 'Process', AppName: 'Andys Exchange Powershell'.
DEBUG: [Authentication]: - Scopes: [].

Confirm
Are you sure you want to perform this action?
Performing the operation "Revoke-MgUserSign_Revoke" on target "Call remote 'UsersRevokeSignInSessions' operation".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"): yes
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
POST

Absolute Uri:
https://graph.microsoft.com/beta/users/25d4d147-<snip>770495d/microsoft.graph.revokeSignInSessions

Headers:
FeatureFlag                   : 00000047
Cache-Control                 : no-store, no-cache
SdkVersion                    : graph-powershell/1.9.2,Graph-dotnet-1.25.1
User-Agent                    : Mozilla/5.0,(Windows NT 10.0; Microsoft Windows 10.0.22621; en-US),PowerShell/7.3.0,Revoke-MgUserSign_Revoke
Accept-Encoding               : gzip

Body:



DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
OK

Headers:
Cache-Control                 : no-cache
Transfer-Encoding             : chunked
Location                      : https://graph.microsoft.com/
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : e612d8bf-a255-48c4-9c44-01abf8f01ec9
client-request-id             : e612d8bf-a255-48c4-9c44-01abf8f01ec9
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"North Central US","Slice":"E","Ring":"3","ScaleUnit":"003","RoleInstance":"CH01EPF0000BDFA"}}
x-ms-resource-unit            : 1
OData-Version                 : 4.0
Date                          : Tue, 13 Dec 2022 14:38:38 GMT

Body:



DEBUG: [CmdletException]: Received exception with message 'NullReferenceException - Object reference not set to an instance of an object. :    at Microsoft.Graph.PowerShell.Cmdlets.RevokeMgUserSign_Revoke.onOk(HttpResponseMessage responseMessage, Task`1 response)
   at Microsoft.Graph.PowerShell.UsersActions.UsersRevokeSignInSessions_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.UsersActions.UsersRevokeSignInSessions_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.UsersActions.UsersRevokeSignInSessions(String userId, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.Cmdlets.RevokeMgUserSign_Revoke.ProcessRecordAsync()'
Revoke-MgUserSign_Revoke: Object reference not set to an instance of an object.
DEBUG: [CmdletEndProcessing]: - Revoke-MgUserSign end processing.
>Invoke-MgGraphRequest -Uri "https://graph.microsoft.com/v1.0/users/$userid/microsoft.graph.revokeSignInSessions" -Method POST -Body @{}

Name                           Value
----                           -----
value                          True
@odata.context                 https://graph.microsoft.com/v1.0/$metadata#Edm.Boolean```

**Comment by peombwa** [comment]
The bug was fixed in version `1.10.0` - https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1359#issuecomment-1171341051. Please upgrade to the latest version of the module (1.18.0). According to the shared debug log, you are using version `1.9.2`.
