### ISSUE TITLE
Issue running Get-MgUser in v2.0.0-Preview5 - Collection was modified; enumeration operation may not execute. Possible PageSize issue in PS 5.1

### ISSUE THREAD

**Issue by stukey** [microsoftgraph/msgraph-sdk-powershell#1916]
We have an existing PowerShell reporting script that we have recently migrated from the MSOL to Graph PowerShell SDK PS module. We are seeing the script regularly fail with a generic _“An error occurred while sending the request”_ error. We see the same error for Get-MgUser and Get-MgDevice cmdlets. The cmdlets return results, but not all results that are available in the tenant. We are using the Microsoft Graph PowerShell SDK module version 2.0.0-preview5 (and also tested in preview8). We are authenticating using App Only authentication via custom AAD app Client Id and Client Secret (hence why we are using v2.00 rather than v1). We’re running under PowerShell 5.1. I believe the error could be related to PageSize since we have over 140,000 users and 200,000+ devices in our tenant. This seems similar to a previously reported issue: https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1192, which was supposed to be fixed.

I've confirmed that setting the PageSize to 500 avoids the error in both the Get-MgUser and Get-MgDevice cmdlets.

Example code:
 
```
[array]$tmpUsers = Get-MgUser -All -Property City, Country, Department, OnPremisesProvisioningErrors, DisplayName, GivenName, OnPremisesImmutableId, OnPremisesLastSyncDateTime, Surname, LastPasswordChangeDateTime, AssignedLicenses, LicenseAssignmentStates, MobilePhone, Id, OfficeLocation, ProvisionedPlans, BusinessPhones, PostalCode, UsageLocation, DeletedDateTime, State, StreetAddress, SignInSessionsValidFromDateTime, JobTitle, UserPrincipalName, UserType, CreatedDateTime
 
Get-MgUser : An error occurred while sending the request.
 
At line:1 char:1
+ [array]$tmpUsers = Get-MgUser -All -Property City, Country, Departmen ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgUser_List], HttpRequestException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgUser_List
 
$error | FL -Force
 
writeErrorStream      : True
Exception             : System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
                           at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
                           at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
                           at System.Net.Http.Headers.HttpHeaders.<GetEnumerator>d__20.MoveNext()
                           at System.Net.Http.Headers.HttpHeaders.ToString()
                           at System.Net.Http.WinHttpHandler.AddRequestHeaders(SafeWinHttpHandle requestHandle, HttpRequestMessage requestMessage, CookieContainer cookies,
                        DecompressionMethods manuallyProcessedDecompressionMethods)
                           at System.Net.Http.WinHttpHandler.<StartRequestAsync>d__122.MoveNext()
                           --- End of inner exception stack trace ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.Graph.RedirectHandler.<SendAsync>d__6.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.Graph.RetryHandler.<SendAsync>d__9.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.Graph.CompressionHandler.<SendAsync>d__2.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.Graph.AuthenticationHandler.<SendAsync>d__16.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.Graph.PowerShell.Users.<UsersUserListUser_Call>d__377.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at Microsoft.Graph.PowerShell.Users.<UsersUserListUser_Call>d__377.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at Microsoft.Graph.PowerShell.Cmdlets.GetMgUser_List.<on2Xx>d__86.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.Graph.PowerShell.Users.<UsersUserListUser_Call>d__377.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at Microsoft.Graph.PowerShell.Users.<UsersUserListUser_Call>d__377.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.Graph.PowerShell.Users.<UsersUserListUser>d__375.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.Graph.PowerShell.Cmdlets.GetMgUser_List.<ProcessRecordAsync>d__84.MoveNext()
TargetObject          :
CategoryInfo          : NotSpecified: (:) [Get-MgUser_List], HttpRequestException
FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgUser_List
ErrorDetails          :
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Get-MgUser<Process>, C:\Program Files\WindowsPowerShell\Modules\Microsoft.Graph.Users\2.0.0\exports\ProxyCmdletDefinitions.ps1: line 5854
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {0, 1}
PSMessageDetails      :
```

**Comment by SeniorConsulting** [comment]
Thanks for documenting this.

Hmm. I've had this issue on single user write methods before too, so I'm not sure whether setting page size is the fix (though I'll definitely investigate this in my scripts/environment):
 - Update-MgUser
 - Get-MgApplication

And others

![image](https://user-images.githubusercontent.com/110941550/229936701-5d2fdfaf-3142-4e3a-ad46-80269a22346c.png)


I think peombwa is aware of this already, over in #1872

**Comment by peombwa** [comment]
Thanks for bringing this to our attention and the detailed logs!

We will investigate and provide a fix in v2. As a workaround, you can consider using PowerShell 7 since the issue is isolated to PowerShell 5.1.

**Comment by CarolKigoonya** [comment]
Hello @SeniorConsulting, my name is Carol, the new MS Graph PowerShell PM. We have identified you as one of the recipients of an [early adopter program](https://devblogs.microsoft.com/microsoft365dev/microsoft-graph-early-adopter-recognition-program/). Please share your email address with me so that we can send the badge to you.

**Comment by peombwa** [comment]
Thanks for your patience as we investigated the issue.

I've traced the root cause to how request headers are handled in the underlaying `WinHttpHandler`. In v2, the Microsoft Graph .NET Core SDK defaults to `WinHttpHandler` as its final HTTP handler when running on .NET Fx (PowerShell 5.1). The bug will be fixed by #2028.

**Comment by stukey** [comment]
Thanks for the update @peombwa.

**Comment by CarolKigoonya** [comment]
@SeniorConsulting please send me your first and last name as well

**Comment by SeniorConsulting** [comment]
Hi Carol - I'm Glenn Senior.

Thanks for the mention. Given that this thread was created primarily by Stukey, I was wondering if you'd assessed his eligibility too :)

**Comment by JeremyTBradshaw** [comment]
@peombwa FYI, I'm seeing this issue with New-MgSiteListItem:

```powershell
New-MgSiteListItem : An error occurred while sending the request.
At line:1 char:36
+ ... s[0..19]) { New-MgSiteListItem -SiteId $psd1.app2.siteId -ListId $psd ...
+                 ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [New-MgSiteListItem_CreateExpanded], HttpRequestException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.NewMgSiteListItem_CreateExpanded

PS C:\Users\MYUSER> $error[0].exception |fl -force


Message        : An error occurred while sending the request.
Data           : {}
InnerException : System.InvalidOperationException: Collection was modified; enumeration operation may not execute.
                    at System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
                    at System.Collections.Generic.Dictionary`2.Enumerator.MoveNext()
                    at System.Net.Http.Headers.HttpHeaders.<GetEnumerator>d__20.MoveNext()
                    at System.Net.Http.Headers.HttpHeaders.ToString()
                    at System.Net.Http.WinHttpHandler.AddRequestHeaders(SafeWinHttpHandle requestHandle, HttpRequestMessage
                 requestMessage, CookieContainer cookies, DecompressionMethods manuallyProcessedDecompressionMethods)
                    at System.Net.Http.WinHttpHandler.<StartRequestAsync>d__122.MoveNext()
TargetSite     : Void Throw()
StackTrace     :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Graph.RedirectHandler.<SendAsync>d__6.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Graph.RetryHandler.<SendAsync>d__9.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Graph.CompressionHandler.<SendAsync>d__2.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Graph.AuthenticationHandler.<SendAsync>d__16.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Graph.PowerShell.Sites.<SiteListCreateItem_Call>d__3742.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at Microsoft.Graph.PowerShell.Sites.<SiteListCreateItem_Call>d__3742.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Graph.PowerShell.Sites.<SiteListCreateItem>d__3740.MoveNext()
                 --- End of stack trace from previous location where exception was thrown ---
                    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                    at Microsoft.Graph.PowerShell.Cmdlets.NewMgSiteListItem_CreateExpanded.<ProcessRecordAsync>d__116.MoveNext()
HelpLink       :
Source         : mscorlib
HResult        : -2146233088
```
I've tried everything under the sun to make sure I'm not modifying any collection during enumeration.  I'm preparing perfect hashtables which are generally working. It's randomly every few that fail.  Doesn't matter if I add a 200-500ms delay for each item, and it's not always the same items that fail.  So based on all my testing, trial and error, I feel it's the cmdlet itself that is committing this supposed crime of modifying a collection.

Considering this, and [your update on May 22](https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1916#issuecomment-1557981423), do you think this will also be fixed?  I see that https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/2028 was already merged, so I'm not sure what to expect.

**Comment by peombwa** [comment]
@JeremyTBradshaw, bug fix #2028 just shipped as part of [2.0.0-rc3](https://github.com/microsoftgraph/msgraph-sdk-powershell/releases/tag/2.0.0-rc3) release. Can you confirm if 2.0.0-rc3 addresses the issue for you?

**Comment by JeremyTBradshaw** [comment]
Will do soon @peombwa .  And will edit this.  Probably tomorrow, but thanks and here's hoping.

**Comment by stukey** [comment]
@peombwa I am currently testing with RC3 and will report back soon. Since it was an intermittent issue, it's not easy to repo. Thanks.

**Comment by CarolKigoonya** [comment]
> 

Thanks, Senior. We took multiple interactions into consideration, and we will be running multiple initiatives to award user engagement.

**Comment by stukey** [comment]
@peombwa So far in my testing with RC3, I am no longer seeing the errors when running Get-MgUser for all users in the tenant.

**Comment by peombwa** [comment]
@stukey, thanks for confirming. I'll proceed to close the issue as fixed. Please feel free to open a new issue if the problem happens again.

I would also like to extend my gratitude to everyone on the thread for their assistance in identifying and providing reproducible steps that aided in resolving the bug.
