### ISSUE TITLE
Update-MgDeviceManagementDeviceConfiguration for editionUpgradeConfiguration issue

### ISSUE THREAD

**Issue by William-Francillette** [microsoftgraph/msgraph-sdk-powershell#1930]
The update command of Update-MgDeviceManagementDeviceConfiguration for editionUpgradeConfiguration is throwing an error despite the update succeed properly

This is my code
```
$up=@{
    DisplayName           = "Edition upgrade and mode switch";
    License               = "";
    LicenseType           = "productKey";
    ProductKey            = "11111-22222-33333-44444-55556";
    SupportsScopeTags     = $True;
    TargetEdition         = "windows10Professional";
    WindowsSMode          = "block";
}

Update-MgDeviceManagementDeviceConfiguration -DeviceConfigurationId "3e4222e0-c172-4081-bf9a-2e17ddfc34ca" -BodyParameter $up -debug
```

And this is debug trace:

```
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PATCH

Absolute Uri:
https://graph.microsoft.com/beta/deviceManagement/deviceConfigurations/3e4222e0-c172-4081-bf9a-2e17ddfc34ca

Headers:


Body:
{
  "TargetEdition": "windows10Professional",
  "WindowsSMode": "block",
  "ProductKey": "11111-22222-33333-44444-55556",
  "LicenseType": "productKey",
  "License": "",
  "displayName": "Edition upgrade and mode switch"
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : a9f9b218-4476-4899-a685-34f0f0ffffe2
client-request-id             : a9f9b218-4476-4899-a685-34f0f0ffffe2
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"UK South","Slice":"E","Ring":"3","ScaleUnit":"003","RoleInstance":"LO2PEPF00001688"}}
Date                          : Mon, 10 Apr 2023 18:18:59 GMT

Body:
{
  "error": {
    "code": "ModelValidationFailure",
    "message": "Exception has been thrown by the target of an invocation.",
    "innerError": {
      "message": "Exception has been thrown by the target of an invocation.",
      "date": "2023-04-10T18:18:59",
      "request-id": "a9f9b218-4476-4899-a685-34f0f0ffffe2",
      "client-request-id": "a9f9b218-4476-4899-a685-34f0f0ffffe2"
    }
  }
}


Update-MgDeviceManagementDeviceConfiguration : Exception has been thrown by the target of an invocation.
At line:11 char:1
+ Update-MgDeviceManagementDeviceConfiguration -DeviceConfigurationId " ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ DeviceConfigu...onfiguration1 }:<>f__AnonymousType203`2) [Update-MgDevice...guration_Update], RestException`1
    + FullyQualifiedErrorId : ModelValidationFailure,Microsoft.Graph.PowerShell.Cmdlets.UpdateMgDeviceManagementDeviceConfiguration_Update
DEBUG: [CmdletEndProcessing]: - Update-MgDeviceManagementDeviceConfiguration end processing.
```

Just to confirm the productkey has updated successfully but the command still thrown the error

**Comment by peombwa** [comment]
Thanks for following up on this.

The response error message in `-Debug` output points to this being a service issue or an issue with the object being set on `-BodyParameter`. The error message can be [reproduced in Graph Explorer](https://developer.microsoft.com/en-us/graph/graph-explorer?request=deviceManagement%2FdeviceConfigurations%2F9f192cfc-d3da-4313-b41c-63b220cdc0a7&method=PATCH&version=beta&GraphUrl=https://graph.microsoft.com&requestBody=eyJUYXJnZXRFZGl0aW9uIjoid2luZG93czEwUHJvZmVzc2lvbmFsIiwiV2luZG93c1NNb2RlIjoiYmxvY2siLCJQcm9kdWN0S2V5IjoiMTExMTEtMjIyMjItMzMzMzMtNDQ0NDQtNTU1NTYiLCJMaWNlbnNlVHlwZSI6InByb2R1Y3RLZXkiLCJMaWNlbnNlIjoiIiwiZGlzcGxheU5hbWUiOiJFZGl0aW9uIHVwZ3JhZGUgYW5kIG1vZGUgc3dpdGNoIn0=) by making a REST call using the provided request body. Please open a ticket/question at https://developer.microsoft.com/en-us/graph/support to follow up with the API experts.

Remember to include the `requestId` and `date` of the affected calls in your ticket/question. See [Microsoft Graph PowerShell module troubleshooting guide](https://learn.microsoft.com/en-us/powershell/microsoftgraph/troubleshooting?view=graph-powershell-1.0#using--debug) for more details. 

This repository is intended for issues related to the functionality of the module. We may not be the best place to answer some queries that are tied to the functionality of the API.

**Comment by William-Francillette** [comment]
Hi Peter @peombwa ,

The model validation error was because I was missing the @odata.type  but it still doesn't work and found some issues when using a service principal and certificate thumbprint as detailed below

Using the Graph Explorer or delegated permissions no problem

Graph Explorer
![image](https://user-images.githubusercontent.com/79221284/232189997-b593c06c-a6b4-4697-858e-7de9f21b661f.png)

Delegated permissions
```
DEBUG: [CmdletBeginProcessing]: - Update-MgDeviceManagementDeviceConfiguration begin processing with parameterSet 'Update'.
DEBUG: [Authentication]: - AuthType: 'Delegated', AuthProviderType: 'InteractiveAuthenticationProvider', ContextScope: 'CurrentUser', AppName: 'Microsoft Graph PowerShell'.
DEBUG: [Authentication]: - Scopes: [DeviceManagementApps.Read.All, DeviceManagementApps.ReadWrite.All, DeviceManagementConfiguration.Read.All, DeviceManagementConfiguration.ReadWrite.All, DeviceManagementServiceConfi
g.Read.All, DeviceManagementServiceConfig.ReadWrite.All, Domain.Read.All, openid, profile, User.Read, email].
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PATCH

Absolute Uri:
https://graph.microsoft.com/beta/deviceManagement/deviceConfigurations/3e4222e0-c172-4081-bf9a-2e17ddfc34ca

Headers:


Body:
{
  "licenseType": "productKey",
  "windowsSMode": "block",
  "license": "",
  "@odata.type": "#microsoft.graph.editionUpgradeConfiguration",
  "productKey": "12345-12345-12345-12345-1234x",
  "targetEdition": "windows10Professional",
  "description": "",
  "displayName": "Edition upgrade and mode switch - update"
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NoContent

Headers:
Strict-Transport-Security     : max-age=31536000
request-id                    : e7b54044-4901-4759-ad0c-fd4619c6dcd1
client-request-id             : e7b54044-4901-4759-ad0c-fd4619c6dcd1
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"UK South","Slice":"E","Ring":"3","ScaleUnit":"000","RoleInstance":"LN2PEPF0000C710"}}
Date                          : Sat, 15 Apr 2023 06:20:54 GMT

Body:



DEBUG: [CmdletEndProcessing]: - Update-MgDeviceManagementDeviceConfiguration end processing.
```

But when using my service principal it fails for different issues

1. Capitalization

With Capital: failing

```
DEBUG: [CmdletBeginProcessing]: - Update-MgDeviceManagementDeviceConfiguration begin processing with parameterSet 'Update'.
DEBUG: [Authentication]: - AuthType: 'AppOnly', AuthProviderType: 'ClientCredentialProvider', ContextScope: 'Process', AppName: 'M365DSC'.
DEBUG: [Authentication]: - Scopes: [DeviceManagementManagedDevices.Read.All, Policy.ReadWrite.ConditionalAccess, User.ReadWrite.All, RoleManagement.Read.Directory, Policy.ReadWrite.ApplicationConfiguration, Applicati
on.ReadWrite.All, Group.Read.All, Directory.ReadWrite.All, DeviceManagementServiceConfig.Read.All, Group.ReadWrite.All, Directory.Read.All, User.Read.All, Agreement.Read.All, DeviceManagementServiceConfig.ReadWrite.A
ll, GroupMember.Read.All, Organization.ReadWrite.All, DeviceManagementConfiguration.Read.All, DeviceManagementManagedDevices.ReadWrite.All, User.ManageIdentities.All, Organization.Read.All, RoleManagement.ReadWrite.D
irectory, GroupMember.ReadWrite.All, Policy.Read.All, DeviceManagementConfiguration.ReadWrite.All, Application.Read.All, DeviceManagementApps.ReadWrite.All, DeviceManagementApps.Read.All, Agreement.ReadWrite.All, Pol
icy.Read.ConditionalAccess, UserAuthenticationMethod.Read.All, UserAuthenticationMethod.ReadWrite.All, EntitlementManagement.Read.All, EntitlementManagement.ReadWrite.All, APIConnectors.Read.All, AppRoleAssignment.Re
adWrite.All, Reports.Read.All].
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PATCH

Absolute Uri:
https://graph.microsoft.com/beta/deviceManagement/deviceConfigurations/3e4222e0-c172-4081-bf9a-2e17ddfc34ca

Headers:


Body:
{
  "WindowsSMode": "block",
  "@odata.type": "#microsoft.graph.editionUpgradeConfiguration"
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
BadRequest

Headers:
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : a3c70986-c27e-4f04-9c36-f20e24315354
client-request-id             : a3c70986-c27e-4f04-9c36-f20e24315354
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"UK South","Slice":"E","Ring":"3","ScaleUnit":"002","RoleInstance":"LO1PEPF0000060D"}}
Date                          : Sat, 15 Apr 2023 06:50:59 GMT

Body:
{
  "error": {
    "code": "ModelValidationFailure",
    "message": "The property 'WindowsSMode' does not exist on type 'microsoft.management.services.api.editionUpgradeConfiguration'. Make sure to only use property names that are defined by the type.",
    "innerError": {
      "message": "The property 'WindowsSMode' does not exist on type 'microsoft.management.services.api.editionUpgradeConfiguration'. Make sure to only use property names that are defined by the type.",
      "date": "2023-04-15T06:50:59",
      "request-id": "a3c70986-c27e-4f04-9c36-f20e24315354",
      "client-request-id": "a3c70986-c27e-4f04-9c36-f20e24315354"
    }
  }
}


Update-MgDeviceManagementDeviceConfiguration : The property 'WindowsSMode' does not exist on type 'microsoft.management.services.api.editionUpgradeConfiguration'. Make sure to only use property names that are 
defined by the type.
At line:12 char:1
+ Update-MgDeviceManagementDeviceConfiguration -DeviceConfigurationId " ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ DeviceConfigu...onfiguration1 }:<>f__AnonymousType203`2) [Update-MgDevice...guration_Update], RestException`1
    + FullyQualifiedErrorId : ModelValidationFailure,Microsoft.Graph.PowerShell.Cmdlets.UpdateMgDeviceManagementDeviceConfiguration_Update
DEBUG: [CmdletEndProcessing]: - Update-MgDeviceManagementDeviceConfiguration end processing.
```
Without capital: success

```
DEBUG: [CmdletBeginProcessing]: - Update-MgDeviceManagementDeviceConfiguration begin processing with parameterSet 'Update'.
DEBUG: [Authentication]: - AuthType: 'AppOnly', AuthProviderType: 'ClientCredentialProvider', ContextScope: 'Process', AppName: 'M365DSC'.
DEBUG: [Authentication]: - Scopes: [DeviceManagementManagedDevices.Read.All, Policy.ReadWrite.ConditionalAccess, User.ReadWrite.All, RoleManagement.Read.Directory, Policy.ReadWrite.ApplicationConfiguration, Applicati
on.ReadWrite.All, Group.Read.All, Directory.ReadWrite.All, DeviceManagementServiceConfig.Read.All, Group.ReadWrite.All, Directory.Read.All, User.Read.All, Agreement.Read.All, DeviceManagementServiceConfig.ReadWrite.A
ll, GroupMember.Read.All, Organization.ReadWrite.All, DeviceManagementConfiguration.Read.All, DeviceManagementManagedDevices.ReadWrite.All, User.ManageIdentities.All, Organization.Read.All, RoleManagement.ReadWrite.D
irectory, GroupMember.ReadWrite.All, Policy.Read.All, DeviceManagementConfiguration.ReadWrite.All, Application.Read.All, DeviceManagementApps.ReadWrite.All, DeviceManagementApps.Read.All, Agreement.ReadWrite.All, Pol
icy.Read.ConditionalAccess, UserAuthenticationMethod.Read.All, UserAuthenticationMethod.ReadWrite.All, EntitlementManagement.Read.All, EntitlementManagement.ReadWrite.All, APIConnectors.Read.All, AppRoleAssignment.Re
adWrite.All, Reports.Read.All].
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PATCH

Absolute Uri:
https://graph.microsoft.com/beta/deviceManagement/deviceConfigurations/3e4222e0-c172-4081-bf9a-2e17ddfc34ca

Headers:


Body:
{
  "windowsSMode": "block",
  "@odata.type": "#microsoft.graph.editionUpgradeConfiguration"
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NoContent

Headers:
Strict-Transport-Security     : max-age=31536000
request-id                    : 16a37a00-1977-4ec0-aaf5-ab44e14153db
client-request-id             : 16a37a00-1977-4ec0-aaf5-ab44e14153db
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"UK South","Slice":"E","Ring":"3","ScaleUnit":"002","RoleInstance":"LO1PEPF0000060D"}}
Date                          : Sat, 15 Apr 2023 06:51:14 GMT

Body:



DEBUG: [CmdletEndProcessing]: - Update-MgDeviceManagementDeviceConfiguration end processing.
```
2. ProductKey parameter

Without productKey: success

```
DEBUG: [CmdletBeginProcessing]: - Update-MgDeviceManagementDeviceConfiguration begin processing with parameterSet 'Update'.
DEBUG: [Authentication]: - AuthType: 'AppOnly', AuthProviderType: 'ClientCredentialProvider', ContextScope: 'Process', AppName: 'M365DSC'.
DEBUG: [Authentication]: - Scopes: [DeviceManagementManagedDevices.Read.All, Policy.ReadWrite.ConditionalAccess, User.ReadWrite.All, RoleManagement.Read.Directory, Policy.ReadWrite.ApplicationConfiguration, Applicati
on.ReadWrite.All, Group.Read.All, Directory.ReadWrite.All, DeviceManagementServiceConfig.Read.All, Group.ReadWrite.All, Directory.Read.All, User.Read.All, Agreement.Read.All, DeviceManagementServiceConfig.ReadWrite.A
ll, GroupMember.Read.All, Organization.ReadWrite.All, DeviceManagementConfiguration.Read.All, DeviceManagementManagedDevices.ReadWrite.All, User.ManageIdentities.All, Organization.Read.All, RoleManagement.ReadWrite.D
irectory, GroupMember.ReadWrite.All, Policy.Read.All, DeviceManagementConfiguration.ReadWrite.All, Application.Read.All, DeviceManagementApps.ReadWrite.All, DeviceManagementApps.Read.All, Agreement.ReadWrite.All, Pol
icy.Read.ConditionalAccess, UserAuthenticationMethod.Read.All, UserAuthenticationMethod.ReadWrite.All, EntitlementManagement.Read.All, EntitlementManagement.ReadWrite.All, APIConnectors.Read.All, AppRoleAssignment.Re
adWrite.All, Reports.Read.All].
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PATCH

Absolute Uri:
https://graph.microsoft.com/beta/deviceManagement/deviceConfigurations/3e4222e0-c172-4081-bf9a-2e17ddfc34ca

Headers:


Body:
{
  "@odata.type": "#microsoft.graph.editionUpgradeConfiguration",
  "targetEdition": "windows10Professional",
  "windowsSMode": "block",
  "licenseType": "productKey",
  "license": "",
  "description": "",
  "displayName": "Edition upgrade and mode switch - update"
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
NoContent

Headers:
Strict-Transport-Security     : max-age=31536000
request-id                    : eb7e3f12-320e-4c1a-aabf-04bb4a5f560e
client-request-id             : eb7e3f12-320e-4c1a-aabf-04bb4a5f560e
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"UK South","Slice":"E","Ring":"3","ScaleUnit":"002","RoleInstance":"LO1PEPF00000FAD"}}
Date                          : Sat, 15 Apr 2023 06:56:48 GMT

Body:



DEBUG: [CmdletEndProcessing]: - Update-MgDeviceManagementDeviceConfiguration end processing.
```

With productKey and an existing connection: failure 

```
DEBUG: [CmdletBeginProcessing]: - Update-MgDeviceManagementDeviceConfiguration begin processing with parameterSet 'Update'.
DEBUG: [Authentication]: - AuthType: 'AppOnly', AuthProviderType: 'ClientCredentialProvider', ContextScope: 'Process', AppName: 'M365DSC'.
DEBUG: [Authentication]: - Scopes: [DeviceManagementManagedDevices.Read.All, Policy.ReadWrite.ConditionalAccess, User.ReadWrite.All, RoleManagement.Read.Directory, Policy.ReadWrite.ApplicationConfiguration, Applicati
on.ReadWrite.All, Group.Read.All, Directory.ReadWrite.All, DeviceManagementServiceConfig.Read.All, Group.ReadWrite.All, Directory.Read.All, User.Read.All, Agreement.Read.All, DeviceManagementServiceConfig.ReadWrite.A
ll, GroupMember.Read.All, Organization.ReadWrite.All, DeviceManagementConfiguration.Read.All, DeviceManagementManagedDevices.ReadWrite.All, User.ManageIdentities.All, Organization.Read.All, RoleManagement.ReadWrite.D
irectory, GroupMember.ReadWrite.All, Policy.Read.All, DeviceManagementConfiguration.ReadWrite.All, Application.Read.All, DeviceManagementApps.ReadWrite.All, DeviceManagementApps.Read.All, Agreement.ReadWrite.All, Pol
icy.Read.ConditionalAccess, UserAuthenticationMethod.Read.All, UserAuthenticationMethod.ReadWrite.All, EntitlementManagement.Read.All, EntitlementManagement.ReadWrite.All, APIConnectors.Read.All, AppRoleAssignment.Re
adWrite.All, Reports.Read.All].
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PATCH

Absolute Uri:
https://graph.microsoft.com/beta/deviceManagement/deviceConfigurations/3e4222e0-c172-4081-bf9a-2e17ddfc34ca

Headers:


Body:
{
  "licenseType": "productKey",
  "windowsSMode": "block",
  "license": "",
  "@odata.type": "#microsoft.graph.editionUpgradeConfiguration",
  "productKey": "12345-12345-12345-12345-12345",
  "targetEdition": "windows10Professional",
  "description": "",
  "displayName": "Edition upgrade and mode switch - update"
}


DEBUG: [CmdletException]: Received exception with message 'TaskCanceledException - A task was canceled. :    at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.DeviceManagement.<DeviceManagementUpdateDeviceConfigurations_Call>d__3696.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Graph.PowerShell.DeviceManagement.<DeviceManagementUpdateDeviceConfigurations_Call>d__3696.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.DeviceManagement.<DeviceManagementUpdateDeviceConfigurations>d__3690.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Cmdlets.UpdateMgDeviceManagementDeviceConfiguration_Update.<ProcessRecordAsync>d__57.MoveNext()'
Update-MgDeviceManagementDeviceConfiguration : A task was canceled.
At line:12 char:1
+ Update-MgDeviceManagementDeviceConfiguration -DeviceConfigurationId " ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Update-MgDevice...guration_Update], TaskCanceledException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.UpdateMgDeviceManagementDeviceConfiguration_Update
 
DEBUG: [CmdletEndProcessing]: - Update-MgDeviceManagementDeviceConfiguration end processing.
```

And another error message after a fresh connection

```
DEBUG: [CmdletBeginProcessing]: - Update-MgDeviceManagementDeviceConfiguration begin processing with parameterSet 'Update'.
DEBUG: [Authentication]: - AuthType: 'AppOnly', AuthProviderType: 'ClientCredentialProvider', ContextScope: 'Process', AppName: 'M365DSC'.
DEBUG: [Authentication]: - Scopes: [DeviceManagementManagedDevices.Read.All, Policy.ReadWrite.ConditionalAccess, User.ReadWrite.All, RoleManagement.Read.Directory, Policy.ReadWrite.ApplicationConfiguration, Applicati
on.ReadWrite.All, Group.Read.All, Directory.ReadWrite.All, DeviceManagementServiceConfig.Read.All, Group.ReadWrite.All, Directory.Read.All, User.Read.All, Agreement.Read.All, DeviceManagementServiceConfig.ReadWrite.A
ll, GroupMember.Read.All, Organization.ReadWrite.All, DeviceManagementConfiguration.Read.All, DeviceManagementManagedDevices.ReadWrite.All, User.ManageIdentities.All, Organization.Read.All, RoleManagement.ReadWrite.D
irectory, GroupMember.ReadWrite.All, Policy.Read.All, DeviceManagementConfiguration.ReadWrite.All, Application.Read.All, DeviceManagementApps.ReadWrite.All, DeviceManagementApps.Read.All, Agreement.ReadWrite.All, Pol
icy.Read.ConditionalAccess, UserAuthenticationMethod.Read.All, UserAuthenticationMethod.ReadWrite.All, EntitlementManagement.Read.All, EntitlementManagement.ReadWrite.All, APIConnectors.Read.All, AppRoleAssignment.Re
adWrite.All, Reports.Read.All].
DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PATCH

Absolute Uri:
https://graph.microsoft.com/beta/deviceManagement/deviceConfigurations/3e4222e0-c172-4081-bf9a-2e17ddfc34ca

Headers:


Body:
{
  "licenseType": "productKey",
  "windowsSMode": "block",
  "license": "",
  "@odata.type": "#microsoft.graph.editionUpgradeConfiguration",
  "productKey": "12345-12345-12345-12345-12345",
  "targetEdition": "windows10Professional",
  "description": "",
  "displayName": "Edition upgrade and mode switch - update"
}


DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Unauthorized

Headers:
Transfer-Encoding             : chunked
Vary                          : Accept-Encoding
Strict-Transport-Security     : max-age=31536000
request-id                    : 017cd45b-254a-4dcc-9f85-a70cf3f5c097
client-request-id             : 017cd45b-254a-4dcc-9f85-a70cf3f5c097
x-ms-ags-diagnostic           : {"ServerInfo":{"DataCenter":"UK South","Slice":"E","Ring":"3","ScaleUnit":"000","RoleInstance":"LN2PEPF0000CFF1"}}
Date                          : Sat, 15 Apr 2023 07:04:16 GMT

Body:
{
  "error": {
    "code": "Forbidden",
    "message": "{\r\n  \"_version\": 3,\r\n  \"Message\": \"An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 017cd45b-254a-4dcc-9f85-a70cf3f5c097 - Url:
 https://fef.amsub0502.manage.microsoft.com/DeviceConfiguration_2304/StatelessDeviceConfigurationFEService/deviceManagement/deviceConfigurations('3e4222e0-c172-4081-bf9a-2e17ddfc34ca')?api-version=5023-01-25\",\r\n  
\"CustomApiErrorPhrase\": \"\",\r\n  \"RetryAfter\": null,\r\n  \"ErrorSourceService\": \"\",\r\n  \"HttpHeaders\": \"{\\\"WWW-Authenticate\\\":\\\"Bearer realm=\\\\\\\"urn:intune:service,c9546a06-e99e-41a4-8644-e46d
735e85c0,f0f3c450-59bf-4f0d-b1b2-0ef84ddfe3c7,3e9c57b9-808d-4aa0-9500-4b2d369279e7\\\\\\\"\\\"}\"\r\n}",
    "innerError": {
      "date": "2023-04-15T07:04:17",
      "request-id": "017cd45b-254a-4dcc-9f85-a70cf3f5c097",
      "client-request-id": "017cd45b-254a-4dcc-9f85-a70cf3f5c097"
    }
  }
}


Update-MgDeviceManagementDeviceConfiguration : {
  "_version": 3,
  "Message": "An error has occurred - Operation ID (for customer support): 00000000-0000-0000-0000-000000000000 - Activity ID: 017cd45b-254a-4dcc-9f85-a70cf3f5c097 - Url: 
https://fef.amsub0502.manage.microsoft.com/DeviceConfiguration_2304/StatelessDeviceConfigurationFEService/deviceManagement/deviceConfigurations('3e4222e0-c172-4081-bf9a-2e17ddfc34ca')?api-version=5023-01-25",
  "CustomApiErrorPhrase": "",
  "RetryAfter": null,
  "ErrorSourceService": "",
  "HttpHeaders": "{\"WWW-Authenticate\":\"Bearer realm=\\\"urn:intune:service,c9546a06-e99e-41a4-8644-e46d735e85c0,f0f3c450-59bf-4f0d-b1b2-0ef84ddfe3c7,3e9c57b9-808d-4aa0-9500-4b2d369279e7\\\"\"}"
}
At line:12 char:1
+ Update-MgDeviceManagementDeviceConfiguration -DeviceConfigurationId " ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: ({ DeviceConfigu...onfiguration1 }:<>f__AnonymousType203`2) [Update-MgDevice...guration_Update], RestException`1
    + FullyQualifiedErrorId : Forbidden,Microsoft.Graph.PowerShell.Cmdlets.UpdateMgDeviceManagementDeviceConfiguration_Update
DEBUG: [CmdletEndProcessing]: - Update-MgDeviceManagementDeviceConfiguration end processing.
```

As I mentioned I have no issue when I remove productKey and this occur only with Service Principal and Certificate authentication - you can see in the above trace that I have modified productKey when using delegated permissions though the Graph Explorer and SDK

Thanks Peter

**Comment by William-Francillette** [comment]
@peombwa Do you need more info re this issue?

**Comment by peombwa** [comment]
Sorry for the delayed response. The issues referenced above are largely service errors. Here is a breakdown of the issues:

> Capitalization.

Intune APIs are known to be case sensitive. The error can be reproduced in Graph Explorer when the wrong case is used. Please maintain lower casing when calling the API. The SDK cannot currently handle case conversion for the API due to missing types in the service schema. See my comments at https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1418#issuecomment-1194255374 for more details.

> With productKey and an existing connection: failure

This looks like a timeout issue when calling the API (the service didn't respond on time, so the HttpClient canceled the request). Which version of the SDK are you using? I can't repro this using the latest version of the SDK.

> And another error message after a fresh connection

This is a service error; the API is responding with a 403 (Forbidden) despite you having assigned `DeviceManagementConfiguration.ReadWrite.All` to the calling service principal. Please follow up with the API owner at https://developer.microsoft.com/en-us/graph/support.
