### ISSUE TITLE
get-mgchat on Powershell 5: Could not load file or assembly 'Microsoft.Graph.Authentication.Core, Version=1.27.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 

### ISSUE THREAD

**Issue by mbourgon** [microsoftgraph/msgraph-sdk-powershell#2037]
Started getting this after updating all modules on my machine yesterday. Just ran an explicit update-module microsoft.graph and it's still busted.

`System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Graph.Authentication.Core, Version=1.27.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' 
`

Connect-mggraph works, but get-mgchat doesn't. Just did an update-module microsoft.graph before running 

**$psversiontable**
PSVersion                      5.1.19041.2673

**get-module -listavailable:**
Script     1.23.0     Microsoft.Graph.Authentication      {Connect-MgGraph, Disconnect-MgGraph, Get-MgContext, Get-MgProfile...}
Script     1.27.0     Microsoft.Graph.Teams               {Add-MgChatMember, Add-MgTeamChannelMember, Add-MgTeamMember, Add-MgTeamPrimaryChannelMember...}
Script     1.26.0     Microsoft.Graph.Teams               {Add-MgChatMember, Add-MgTeamChannelMember, Add-MgTeamMember, Add-MgTeamPrimaryChannelMember...}
Script     1.23.0     Microsoft.Graph.Teams               {Add-MgChatMember, Add-MgTeamChannelMember, Add-MgTeamMember, Add-MgTeamPrimaryChannelMember...}

PS C:\Users\me> try {get-mgchat -ErrorAction Stop -Debug } catch { Write-Host $_.Exception | fl * }
System.AggregateException: One or more errors occurred. ---> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Graph.Authentication.Core, Version=1.27.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
   at Microsoft.Graph.PowerShell.Module.<OnCmdletBeginProcessing>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Graph.PowerShell.Module.OnCmdletBeginProcessing(String id, CancellationToken cancellationToken, Func`1 getEventData, Func`4 signal, InvocationInfo invocationInfo)
   at Microsoft.Graph.PowerShell.Module.<EventHandler>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Module.<Signal>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Cmdlets.GetMgChat_List1.<Microsoft-Graph-PowerShell-Runtime-IEventListener-Signal>d__78.MoveNext()
   --- End of inner exception stack trace ---
   at System.Threading.Tasks.Task.ThrowIfExceptional(Boolean includeTaskCanceledExceptions)
   at System.Threading.Tasks.Task.Wait(Int32 millisecondsTimeout, CancellationToken cancellationToken)
   at Microsoft.Graph.PowerShell.Cmdlets.GetMgChat_List1.BeginProcessing()
   at System.Management.Automation.Cmdlet.DoBeginProcessing()
   at System.Management.Automation.CommandProcessorBase.DoBegin()
---> (Inner Exception #0) System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Graph.Authentication.Core, Version=1.27.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.
File name: 'Microsoft.Graph.Authentication.Core, Version=1.27.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'
   at Microsoft.Graph.PowerShell.Module.<OnCmdletBeginProcessing>d__5.MoveNext()
   at System.Runtime.CompilerServices.AsyncTaskMethodBuilder.Start[TStateMachine](TStateMachine& stateMachine)
   at Microsoft.Graph.PowerShell.Module.OnCmdletBeginProcessing(String id, CancellationToken cancellationToken, Func`1 getEventData, Func`4 signal, InvocationInfo invocationInfo)
   at Microsoft.Graph.PowerShell.Module.<EventHandler>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Module.<Signal>d__35.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Cmdlets.GetMgChat_List1.<Microsoft-Graph-PowerShell-Runtime-IEventListener-Signal>d__78.MoveNext()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
<---

**Comment by SeniorConsulting** [comment]
From your Get-Module command, you can see that you have differing versions of the modules:

> Script 1.23.0 Microsoft.Graph.Authentication {Connect-MgGraph, Disconnect-MgGraph, Get-MgContext, Get-MgProfile...}
> Script 1.27.0 Microsoft.Graph.Teams {Add-MgChatMember, Add-MgTeamChannelMember, Add-MgTeamMember, Add-MgTeamPrimaryChannelMember...}
> Script 1.26.0 Microsoft.Graph.Teams {Add-MgChatMember, Add-MgTeamChannelMember, Add-MgTeamMember, Add-MgTeamPrimaryChannelMember...}
> Script 1.23.0 Microsoft.Graph.Teams {Add-MgChatMember, Add-MgTeamChannelMember, Add-MgTeamMember, Add-MgTeamPrimaryChannelMember...}

So:
- Microsoft.Graph.Authentication = 1.23.0
- Microsoft.Graph.Teams = 1.23.0 - 1.27.0

And in the error you've provided, you've got 
> System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Graph.Authentication.Core, Version=1.27.0.0

So it sounds like the Teams module is looking for Microsoft.Graph.Authentication under version 1.27.0, but can't find it. I've found that sometimes the Microsoft.Graph.Authentication module won't update if it's already been called - it would need to be unloaded first.
Try restarting your PowerShell session, then explictly calling:
`Update-Module Microsoft.Graph.Authentication -RequiredVersion 1.27.0`

Validate that it has loaded with your Get-Module -listavailable command again, and hopefully you'll be sorted.

**Comment by mbourgon** [comment]
@SeniorConsulting Alas, that didn't do it. I did what you suggested and I see 1.27 in there, but it still doesn't choose to use it. I'm at a loss.  Even restarted and tried doing an update-module this morning. I now see 1.13, 1.23, 1.26, and 1.27 of microsoft.graph.authentication.  But same exact error. 

System.IO.FileNotFoundException: Could not load file or assembly 'Microsoft.Graph.Authentication.Core, Version=1.27.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. The system cannot find the file specified.

**Comment by SeniorConsulting** [comment]
It looks like some other people have experienced the same sort of issue you had. The initial error message looked a little bit different, but under the hood it was the same issue. Resolution: Full uninstall and reinstall.

https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/1196#issuecomment-1366701105

**Comment by mbourgon** [comment]
@SeniorConsulting  thanks! And for any others: you need to uninstall all of Microsoft.Graph, then explicitly install force 1.27.00. Just installing microsoft.graph installs multiple incompatible versions.

**Comment by mbourgon** [comment]
still confusing why it doesn't work as expected, but this fixes it. And further convinces me to never update modules. : \

**Comment by mbourgon** [comment]
still confusing why it doesn't work as expected, but this fixes it. And further convinces me to never update modules. : \
