### ISSUE TITLE
Errors retrieving Applications with Managed Identity

### ISSUE THREAD

**Issue by kevball2** [microsoftgraph/msgraph-sdk-powershell#2163]
Thanks for reporting the bug. Please ensure you've gone through the following checklist before opening an issue:
- Make sure you can reproduce this issue using the latest released version of [Microsoft.Graph](https://www.powershellgallery.com/packages/Microsoft.Graph) or [Microsoft.Graph.Beta](https://www.powershellgallery.com/packages/Microsoft.Graph.Beta).
- Please search the existing issues to see if there has been a similar issue filed.
- For issues related to authentication and service errors, please refer to our [troubleshooting guide](https://learn.microsoft.com/powershell/microsoftgraph/troubleshooting). For service issues, please open a question at https://developer.microsoft.com/graph/support.

**Describe the bug**
> Attempting to add a new Application password using a managed Identity for an Azure Function. The command if defaulting to the -confirm switch being included. 

**To Reproduce**
1. connect to MSGraph with Managed Identity (Connect-MgGraph -Identity)
2. Run Add-MGApplicationPassword with required information (Add-MgBetaApplicationPassword -ApplicationId $applicationId -BodyParameter $params -debug
3. Error happens on both 1.0 and Beta version 

**Expected behavior**
> I expect the application password to be added without confirmation *unless* the confirm switch is added. 

**Debug Output**
```
2023-07-14T19:19:34Z   [Verbose]   DEBUG: [CmdletBeginProcessing]: - Add-MgBetaApplicationPassword begin processing with parameterSet 'Add'.
2023-07-14T19:19:34Z   [Verbose]   DEBUG: [Authentication]: - AuthType: 'ManagedIdentity', TokenCredentialType: 'ManagedIdentity', ContextScope: 'Process', AppName: 'func-secretrotation-dev-ugv'.
2023-07-14T19:19:34Z   [Verbose]   DEBUG: [Authentication]: - Scopes: [Application.ReadWrite.OwnedBy].
2023-07-14T19:19:34Z   [Verbose]   DEBUG: [CmdletException]: Received exception with message 'HostException - A command that prompts the user failed because the host program or the command type does not support user interaction. The host was attempting to request confirmation with the following message: Are you sure you want to perform this action?
Performing the operation "Add-MgBetaApplicationPassword_Add" on target "Call remote 'POST /applications/{application-id}/microsoft.graph.addPassword' operation". :    at System.Management.Automation.Internal.Host.InternalHostUserInterface.ThrowPromptNotInteractive(String promptMessage)
   at System.Management.Automation.Internal.Host.InternalHostUserInterface.PromptForChoice(String caption, String message, Collection`1 choices, Int32 defaultChoice)
   at System.Management.Automation.MshCommandRuntime.InquireHelper(String inquireMessage, String inquireCaption, Boolean allowYesToAll, Boolean allowNoToAll, Boolean replaceNoWithHalt, Boolean hasSecurityImpact)
   at System.Management.Automation.MshCommandRuntime.DoShouldProcess(String verboseDescription, String verboseWarning, String caption, ShouldProcessReason& shouldProcessReason)
   at System.Management.Automation.MshCommandRuntime.ShouldProcess(String target)
   at System.Management.Automation.Cmdlet.ShouldProcess(String target)
   at Microsoft.Graph.Beta.PowerShell.Cmdlets.AddMgBetaApplicationPassword_Add.ProcessRecord()'
```

**Module Version**
```
2023-07-14T19:29:26Z   [Information]   OUTPUT: ModuleType Version    PreRelease Name                                ExportedCommands
2023-07-14T19:29:26Z   [Information]   OUTPUT: ---------- -------    ---------- ----                                ----------------
2023-07-14T19:29:26Z   [Information]   OUTPUT: Script     2.1.0                 Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGraph, Disconnect-Mg…
2023-07-14T19:29:26Z   [Information]   OUTPUT: Script     2.1.0                 Microsoft.Graph.Beta.Applications   {Add-MgBetaApplicationKey, Add-MgBetaApplicationPa…
```

**Environment Data**
The azure function is running 7.2

**Screenshots**
> If applicable, add screenshots to help explain your problem.

**Additional context**
> Add any other context about the problem here.

**Comment by peombwa** [comment]
This is by design.

PowerShell will ask for a confirmation on `-Debug` when a command is about to [make a change that's outside the PowerShell environment](https://learn.microsoft.com/en-us/powershell/scripting/developer/cmdlet/requesting-confirmation-from-cmdlets) (in this case, `SupportsShouldProcess` is set to true and `ConfirmImpact` set to `medium`). Please call the command with `-Confirm:$false` to bypass the confirmation.

The same behavior can be seen with native PowerShell commands that make changes external to PowerShell. For example, `New-Item` will prompt for confirmation on `-Debug`:
``` powershell
➜ New-Item "test.txt" -Debug

Confirm
Are you sure you want to perform this action?
Performing the operation "Create File" on target "Destination: C:\Dev\test.txt".
[Y] Yes  [A] Yes to All  [N] No  [L] No to All  [S] Suspend  [?] Help (default is "Y"):
```

**Comment by kevball2** [comment]
thanks @peombwa , I will test this tomorrow.

**Comment by kevball2** [comment]
adding `-confirm:$false`  did not resolve the issue, removing the `-debug` command and attempting to run the command also fails. The error seems to hint that in my scenario (logged in via a function with a managed Identity) does not provide an option to present an interaction to the user. 

```powershell

    $params = @{
      PasswordCredential = @{
        DisplayName = $DisplayName
        endDateTime = $exp
        startDateTime = $nbf
        Confirm = $false
      }
    }

    $password = Add-MgApplicationPassword -ApplicationId $applicationId -BodyParameter $params -debug
```

**Comment by peombwa** [comment]
> ```powershell
>     $params = @{
>       PasswordCredential = @{
>         DisplayName = $DisplayName
>         endDateTime = $exp
>         startDateTime = $nbf
>         Confirm = $false
>       }
>     }
> 
>     $password = Add-MgApplicationPassword -ApplicationId $applicationId -BodyParameter $params -debug
> ```

This won't work because `Confirm` is specified in the `-BodyParameter`, request body that's sent to the service. Confirm is part of PowerShell's mitigation parameters. `-Confirm` should be used as shown below:
``` diff
    $params = @{
      PasswordCredential = @{
        DisplayName = $DisplayName
        endDateTime = $exp
        startDateTime = $nbf
-       # Confirm = $false
      }
    }

# This works in any environment including Azure Function with Managed Identity.
+   $password = Add-MgApplicationPassword -ApplicationId $applicationId -BodyParameter $params -debug -Confirm:$false
```

**Comment by kevball2** [comment]
trying with the recommended command but still no joy
```powershell

    $params = @{
      PasswordCredential = @{
        DisplayName = $DisplayName
        endDateTime = $exp
        startDateTime = $nbf
      }
    }

    $password = Add-MgApplicationPassword -ApplicationId $applicationId -BodyParameter $params -debug -Confirm:$false
```
```
2023-07-27T17:29:12Z   [Verbose]   DEBUG: [Authentication]: - Scopes: [Application.ReadWrite.OwnedBy].
2023-07-27T17:29:12Z   [Verbose]   DEBUG: [CmdletBeginProcessing]: - Add-MgApplicationPassword begin processing with parameterSet 'Add'.
2023-07-27T17:29:12Z   [Verbose]   DEBUG: [Authentication]: - AuthType: 'ManagedIdentity', TokenCredentialType: 'ManagedIdentity', ContextScope: 'Process', AppName: 'func-secretrotation-dev-ugv'.
2023-07-27T17:29:12Z   [Verbose]   DEBUG: [Authentication]: - Scopes: [Application.ReadWrite.OwnedBy].
2023-07-27T17:29:12Z   [Verbose]   DEBUG: [CmdletBeginProcessing]: - Add-MgApplicationPassword begin processing with parameterSet 'Add'.
2023-07-27T17:29:12Z   [Verbose]   DEBUG: [Authentication]: - AuthType: 'ManagedIdentity', TokenCredentialType: 'ManagedIdentity', ContextScope: 'Process', AppName: 'func-secretrotation-dev-ugv'.
2023-07-27T17:29:16Z   [Verbose]   DEBUG: [CmdletException]: Received exception with message 'InvalidOperationException - Unable to perform redirect as Location Header is not set in response :    at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.RetryHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.CompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Graph.PowerShell.Authentication.Handlers.AuthenticationHandler.SendAsync(HttpRequestMessage httpRequestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Graph.PowerShell.Applications.ApplicationAddPassword_Call(HttpRequestMessage request, Func`3 on2Xx, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.Applications.ApplicationAddPassword_Call(HttpRequestMessage request, Func`3 on2Xx, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.Applications.ApplicationAddPassword(String applicationId, IPaths141Ryo0ApplicationsApplicationIdMicrosoftGraphAddpasswordPostRequestbodyContentApplicationJsonSchema body, Func`3 on2Xx, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.Cmdlets.AddMgApplicationPassword_Add.ProcessRecordAsync()'
2023-07-27T17:29:16Z   [Verbose]   DEBUG: [CmdletException]: Received exception with message 'InvalidOperationException - Unable to perform redirect as Location Header is not set in response :    at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.RetryHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.CompressionHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
   at Microsoft.Graph.PowerShell.Authentication.Handlers.AuthenticationHandler.SendAsync(HttpRequestMessage httpRequestMessage, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.Graph.PowerShell.Applications.ApplicationAddPassword_Call(HttpRequestMessage request, Func`3 on2Xx, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.Applications.ApplicationAddPassword_Call(HttpRequestMessage request, Func`3 on2Xx, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.Applications.ApplicationAddPassword(String applicationId, IPaths141Ryo0ApplicationsApplicationIdMicrosoftGraphAddpasswordPostRequestbodyContentApplicationJsonSchema body, Func`3 on2Xx, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.Cmdlets.AddMgApplicationPassword_Add.ProcessRecordAsync()'
2023-07-27T17:29:19Z   [Verbose]   DEBUG: [CmdletEndProcessing]: - Add-MgApplicationPassword end processing.
```

This function is in the azure AzureGovernment, is there a different endpoint or url that I should be setting what would be set after the managed Identity is autheticated with `Connect-MgGraph -Identity`?

**Comment by peombwa** [comment]
Thanks for providing the stack trace.

This is a service issue as per the stack trace at:
> 2023-07-27T17:29:16Z   [Verbose]   DEBUG: [CmdletException]: Received exception with message 'InvalidOperationException - Unable to perform redirect as Location Header is not set in response :    at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.RedirectHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)

It looks like the API responded with a [status code that requires redirection](https://github.com/microsoft/kiota-http-dotnet/blob/848ceaf64bb7d5387b6435f6b679593adb3550a9/src/Middleware/RedirectHandler.cs#L164-L174) with no `Location` header on the response, which goes against HTTP spec. Please open a support ticket at open a support ticket at https://developer.microsoft.com/graph/support for the API owner to investigate.

I can see that other customers have reported similar service issues in the past - https://learn.microsoft.com/en-us/answers/questions/533534/get-v1-0-users-request-gives-302-redirect-with-no and https://stackoverflow.com/questions/63428828/microsoft-graph-subscription-api-started-returning-http-308-with-no-location.

**Comment by kevball2** [comment]
@peombwa  thank you for following up on this! I will get a ticket open and hopefully they can add it to their backlog and resolve it soon.
