### ISSUE TITLE
Send-MgUserMail : One or more errors occurred. 

### ISSUE THREAD

**Issue by cyrkin** [microsoftgraph/msgraph-sdk-powershell#2207]
Hello,

Since I updated the Graph powershell SDK to v2.1 (and now 2.2) I have an error showing every time I am using Send-MgUserMail.
I authenticate interactively to a registered app with the Mail.Send delegated permission.
I does it even when I launch the exact example of the MS documentation : https://learn.microsoft.com/en-us/powershell/module/microsoft.graph.users.actions/send-mgusermail?view=graph-powershell-1.0#example-1-using-the-send-mgusermail-cmdlet

```
VERBOSE: Performing the operation "Send-MgUserMail_SendExpanded" on target "Call remote 'POST /users/{user-id}/microsoft.graph.sendMail' operation".
Send-MgUserMail : One or more errors occurred.
At line:23 char:1
+ Send-MgUserMail -UserId $MsgFrom -Message $params -Verbose
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Send-MgUserMail_SendExpanded], AggregateException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.SendMgUserMail_SendExpanded
```

Good news is that I actually receive the email, everything seems to work as with the previous version, it's just that each time, I got this error message.

Full Debug error message : 
`Send-MgUserMail -UserId $MsgFrom -Message $params -Debug
DEBUG: [CmdletBeginProcessing]: - Send-MgUserMail begin processing with parameterSet 'SendExpanded'.
DEBUG: [Authentication]: - AuthType: 'Delegated', TokenCredentialType: 'InteractiveBrowser', ContextScope: 'CurrentUser', AppName: 'XXX'.
DEBUG: [Authentication]: - Scopes: [Mail.Send, User.Read, profile, openid, email].
Performing the operation "Send-MgUserMail_SendExpanded" on target "Call remote 'POST /users/{user-id}/microsoft.graph.sendMail' operation".
DEBUG: [CmdletException]: Received exception with message 'AggregateException - One or more errors occurred. :    at System.Threading.Tasks.Task`1.GetResultCore(Boolean waitCompletionNotification)
   at Microsoft.Graph.PowerShell.EventFactory.CreateLogEvent(Task`1 message)
   at Microsoft.Graph.PowerShell.Cmdlets.SendMgUserMail_SendExpanded.<>c__DisplayClass62_0.<Microsoft.Graph.PowerShell.Runtime.IEventListener.Signal>b__1()
   at Microsoft.Graph.PowerShell.Cmdlets.SendMgUserMail_SendExpanded.<Microsoft-Graph-PowerShell-Runtime-IEventListener-Signal>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Module.<OnResponseCreated>d__3.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Module.<EventHandler>d__0.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Module.<Signal>d__32.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Cmdlets.SendMgUserMail_SendExpanded.<Microsoft-Graph-PowerShell-Runtime-IEventListener-Signal>d__62.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.UsersActions.<UserSendMail_Call>d__632.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Graph.PowerShell.UsersActions.<UserSendMail_Call>d__632.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.UsersActions.<UserSendMail>d__630.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Cmdlets.SendMgUserMail_SendExpanded.<ProcessRecordAsync>d__64.MoveNext()'

One or more errors occurred.

Send-MgUserMail : One or more errors occurred.
At line:1 char:1
+ Send-MgUserMail -UserId $MsgFrom -Message $params -Debug
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Send-MgUserMail_SendExpanded], AggregateException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.SendMgUserMail_SendExpanded
 
DEBUG: [CmdletEndProcessing]: - Send-MgUserMail end processing.
`

I use VS Code with PSVersion 5.1.19041.3031 and Graph module version 2.2.0.

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

We are currently investigating this issue in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2191. Our preliminary investigation points to an issue with the HTTP implementation in .NET 4.x when cloning the request content. As a workaround, please use PowerShell 7.x to run the commands as we investigate the issue.

Closing as duplicate of https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2191.
