### ISSUE TITLE
Random failures for Set-MgUserPhotoContent

### ISSUE THREAD

**Issue by danchevv** [microsoftgraph/msgraph-sdk-powershell#2360]
**Describe the bug**
> When running the command multiple times in a short amount of times (i.e. a script) the command seems to fail at random.

**To Reproduce**
1. Have a script that uploads pictures for multiple users - I was able to get this error with batches of up to 20 users.
2. At some point some user will fail. If you run the single command for that user with the same parameters, it will succeed

**Expected behavior**
Either a clear error on what the problem was or the picture to be changed successfully. 

**Debug Output**
DEBUG: [CmdletException]: Received exception with message 'HttpRequestException - An error occurred while sending the request. :    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.RedirectHandler.<SendAsync>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.RetryHandler.<SendAsync>d__7.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.CompressionHandler.<SendAsync>d__1.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Authentication.Handlers.AuthenticationHandler.<SendAsync>d__12.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Users.<UserSetPhotoContent_Call>d__441.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Graph.PowerShell.Users.<UserSetPhotoContent_Call>d__441.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Users.<UserSetPhotoContent>d__439.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Cmdlets.SetMgUserPhotoContent_Set.<ProcessRecordAsync>d__57.MoveNext()'
DEBUG: [CmdletException]: Received exception with message 'PipelineStoppedException - The pipeline has been stopped. :    at System.Management.Automation.MshCommandRuntime._WriteErrorSkipAllowCheck(ErrorRecord errorRecord, Nullable`1 actionPreference)
   at System.Management.Automation.MshCommandRuntime.DoWriteError(Object obj)
   at System.Security.SecurityContext.Run(SecurityContext securityContext, ContextCallback callback, Object state)
   at System.Management.Automation.MshCommandRuntime.WriteError(ErrorRecord errorRecord, Boolean overrideInquire)
   at System.Management.Automation.Cmdlet.WriteError(ErrorRecord errorRecord)
   at Microsoft.Graph.PowerShell.Cmdlets.SetMgUserPhotoContent_Set.<ProcessRecordAsync>d__57.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Graph.PowerShell.Cmdlets.SetMgUserPhotoContent_Set.<ProcessRecordAsync>d__57.MoveNext()'

**Module Version**
Get-Module Microsoft.Graph*

ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     2.6.1      Microsoft.Graph.Authentication      {Add-MgEnvironment, Connect-MgGraph, Disconnect-MgGraph, G...

**Environment Data**
$PSVersionTable

Name                           Value
----                           -----
PSVersion                      5.1.20348.1850
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.20348.1850
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1

**Screenshots**
N/A

**Additional context**
We are authenticating with a client secret to an application which has the necessary permissions to change the pictures. Again, this seems to work for most users, but in some odd cases it fails for some for no valid reason. Usually it tends to succeed for 80-90% of the users, and on rare occasions it won't fail at all. Is there some throttling mechanism at hand here?

**Comment by peombwa** [comment]
Thanks for bringing this to our attention.

Could you please share the output of `$error[0] | fl -Force` right after the error has occurred to help us understand the error as we are not able to repro on our end. Also, does error occur in PowerShell 7, the latest version of PowerShell?

**Comment by tkudya** [comment]
@peombwa , we are not using Powershell 7 yet
![image](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/78653328/53d2af8b-6104-4e23-9698-8828094ecc65)

**Comment by yudicon** [comment]
Same here as @peombwa. But on every upload try. Same in pwsh7.

**Comment by danchevv** [comment]
Here are the log outputs for Powershell 6:
`

Exception             : System.Net.Http.HttpRequestException: An error occurred while sending the 
                        request. ---> System.Net.WebException: The request was aborted: The 
                        request was canceled. ---> System.IO.IOException: Cannot close stream 
                        until all bytes are written.
                           at System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean 
                        aborting)
                           --- End of inner exception stack trace ---
                           at System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean 
                        aborting)
                           at System.Net.ConnectStream.System.Net.ICloseEx.CloseEx(CloseExState 
                        closeState)
                           at System.Net.ConnectStream.Dispose(Boolean disposing)
                           at System.IO.Stream.Close()
                           at System.Net.Http.HttpClientHandler.<>c__DisplayClass109_0.<GetRequestS
                        treamCallback>b__0(Task task)
                           --- End of inner exception stack trace ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebugg
                        erNotification(Task task)
                           at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.RedirectHandler.<Se
                        ndAsync>d__5.MoveNext()
                        --- End of stack trace from previous location where exception was thrown 
                        ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebugg
                        erNotification(Task task)
                           at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.RetryHandler.<SendA
                        sync>d__7.MoveNext()
                        --- End of stack trace from previous location where exception was thrown 
                        ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebugg
                        erNotification(Task task)
                           at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.CompressionHandler.
                        <SendAsync>d__1.MoveNext()
                        --- End of stack trace from previous location where exception was thrown 
                        ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebugg
                        erNotification(Task task)
                           at Microsoft.Graph.PowerShell.Authentication.Handlers.AuthenticationHand
                        ler.<SendAsync>d__12.MoveNext()
                        --- End of stack trace from previous location where exception was thrown 
                        ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebugg
                        erNotification(Task task)
                           at Microsoft.Graph.PowerShell.Users.<UserSetPhotoContent_Call>d__441.Mov
                        eNext()
                        --- End of stack trace from previous location where exception was thrown 
                        ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at Microsoft.Graph.PowerShell.Users.<UserSetPhotoContent_Call>d__441.Mov
                        eNext()
                        --- End of stack trace from previous location where exception was thrown 
                        ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebugg
                        erNotification(Task task)
                           at 
                        Microsoft.Graph.PowerShell.Users.<UserSetPhotoContent>d__439.MoveNext()
                        --- End of stack trace from previous location where exception was thrown 
                        ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebugg
                        erNotification(Task task)
                           at Microsoft.Graph.PowerShell.Cmdlets.SetMgUserPhotoContent_Set.<Process
                        RecordAsync>d__57.MoveNext()
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Set-MgUserPhotoContent_Set], HttpRequestException
FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.SetMgUserPhotoContent_Set
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Set-MgUserPhotoContent<Process>, C:\Program Files\WindowsPowerShell\Modu
                        les\Microsoft.Graph.Users\2.6.1\exports\ProxyCmdletDefinitions.ps1: line 
                        47761
                        at <REDACTED due to PII>, 
                        <REDACTED due to PII>.ps1: line 204
                        at <ScriptBlock>, 
                        <REDACTED due to PII>.ps1: line 314
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo : {}
PSMessageDetails      : 
`

I'll post an update once I test with Powershell 7.

**Comment by tschwa21** [comment]
I am having the same issue. On PowerShell 7 with Microsoft.Graph.Users module version 2.2. Below is the error


`writeErrorStream      : True
Exception             : System.Net.Http.HttpRequestException: An error occurred while sending the request. ---> System.Net.WebException: The request was aborted: The request was canceled. ---> System.IO.IOException: Cannot 
                        close stream until all bytes are written.
                           at System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean aborting)
                           --- End of inner exception stack trace ---
                           at System.Net.ConnectStream.CloseInternal(Boolean internalCall, Boolean aborting)
                           at System.Net.ConnectStream.System.Net.ICloseEx.CloseEx(CloseExState closeState)
                           at System.Net.ConnectStream.Dispose(Boolean disposing)
                           at System.IO.Stream.Close()
                           at System.Net.Http.HttpClientHandler.<>c__DisplayClass109_0.<GetRequestStreamCallback>b__0(Task task)
                           --- End of inner exception stack trace ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.RedirectHandler.<SendAsync>d__5.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.RetryHandler.<SendAsync>d__7.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.Kiota.Http.HttpClientLibrary.Middleware.CompressionHandler.<SendAsync>d__1.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.Graph.PowerShell.Authentication.Handlers.AuthenticationHandler.<SendAsync>d__12.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.Graph.PowerShell.Users.<UserSetPhotoContent_Call>d__441.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at Microsoft.Graph.PowerShell.Users.<UserSetPhotoContent_Call>d__441.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.Graph.PowerShell.Users.<UserSetPhotoContent>d__439.MoveNext()
                        --- End of stack trace from previous location where exception was thrown ---
                           at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
                           at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
                           at Microsoft.Graph.PowerShell.Cmdlets.SetMgUserPhotoContent_Set.<ProcessRecordAsync>d__57.MoveNext()
TargetObject          : 
CategoryInfo          : NotSpecified: (:) [Set-MgUserPhotoContent_Set], HttpRequestException
FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.SetMgUserPhotoContent_Set
ErrorDetails          : 
InvocationInfo        : System.Management.Automation.InvocationInfo
ScriptStackTrace      : at Set-MgUserPhotoContent<Process>, C:\Users\thomas.schwoerer\Documents\WindowsPowerShell\Modules\Microsoft.graph.users\2.2.0\exports\ProxyCmdletDefinitions.ps1: line 47552
                        at <ScriptBlock>, C:\Scripts\Weekly Maintenance\Sync User Photos Changes Only.ps1: line 274
PipelineIterationInfo : {0, 1}
PSMessageDetails      :

**Comment by danchevv** [comment]
As of now, I have not been able to reproduce the issue with Powershell 7. I installed it via the x64 MSI file and did not add it to the path nor ticked any other checkbox during the installation. Seems to be working for now.

**Comment by peombwa** [comment]
> As of now, I have not been able to reproduce the issue with Powershell 7. I installed it via the x64 MSI file and did not add it to the path nor ticked any other checkbox during the installation. Seems to be working for now.

Thanks for confirming and providing the stack trace. We will use this issue to investigate why the error is occurring in PowerShell 5.1.

@tschwa21, you may want to first update your SDK to version 2.8.0. Several improvements and bug fixes have been made to the SDK since v2.2.0. See release notes at https://github.com/microsoftgraph/msgraph-sdk-powershell/releases for more details.

**Comment by ztrhgf** [comment]
Same issue here on 2.8.0 version. On my Windows 10 system it works fine, but on Server 2016 it fails every time with error "An error occurred while sending the request."

**Comment by yudicon** [comment]
In my case there is no chance to get a photo uploaded. Regardless of the operating system. What is the correct way to handle this? The retirement of the old powershell commands is soon and error handling or error information of the new Graph APIs is horrible. We can't just sit around try to change sizes and hope that the request will go through. Please provide accurate error messages, we can work with.

**Comment by tschwa21** [comment]
> > As of now, I have not been able to reproduce the issue with Powershell 7. I installed it via the x64 MSI file and did not add it to the path nor ticked any other checkbox during the installation. Seems to be working for now.
> 
> Thanks for confirming and providing the stack trace. We will use this issue to investigate why the error is occurring in PowerShell 5.1.
> 
> @tschwa21, you may want to first update your SDK to version 2.8.0. Several improvements and bug fixes have been made to the SDK since v2.2.0. See release notes at https://github.com/microsoftgraph/msgraph-sdk-powershell/releases for more details.

Still having the issue on 2.8.0.

**Comment by TheEnderPrime** [comment]
I am also having this issue on PS5.1 with SDK 2.8.0. Every single photo I try to upload causes the error.

**Comment by dclarkSSOE** [comment]
Also having this issue with PS5.1.

**Comment by tkudya** [comment]
I am still having issues on Powershell 5.1 with graph 2.11.1

**Comment by MaKraMc** [comment]
This is still happening with module version 2.19.0 in PS5.1 Desktop.

**Comment by nicolaibaralmueller** [comment]
Same error using Azure Automation account runbook with powershell 5.1. All MgGraph updated to latest.

**Comment by PSBoon825** [comment]
Hello, is there no solution to this issue? Still not working with 2.20.0... I was forced to use this command since Set-UserPhoto was deprecated but Set-MgUserPhotoContent does not work...

I can't find any solution on the Internet.

Getting the same errors:
Set-MgUserPhotoContent : An error occurred while sending the request.
CategoryInfo          : NotSpecified: (:) [Set-MgUserPhotoContent_Set], HttpRequestException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.SetMgUserPhotoContent_Set

Thanks!

**Comment by tkudya** [comment]
@PSBoon825 - I have converted my script to use powershell graph api instead, its more reliable than this command

**Comment by ztrhgf** [comment]
I will repeat myself, but what "solved" this issue for me was to resize the images to the height of 188 pixels and add some wait time between Set-MgUserPhotoContent calls.

**Comment by PSBoon825** [comment]
@tkudya Thanks for the hint, this looks much more complicated though since I'm not experienced with API calls. Do you happen to have some example code?

**Comment by PSBoon825** [comment]
@ztrhgf Thanks for your reply. This happens to me even when running the command only once sometimes. Sometimes it works, sometimes it doesn't. Very unreliable. I read somewhere that the images should be converted to 648x648 for the MS cloud uploads, so isn't 188 against the "best practice"?

**Comment by timayabi2020** [comment]
Hello all. I did not manage to replicate the issue while doing a batch update against the API. I tried using the cmdlet and directly invoking the API. However, if you still experiencing the issue, you can explore @ztrhgf solution of introducing a sleep time or making the script asynchronous. 

For further clarifications about the service, we may not be best placed to give an answer because this seems to be an API issue. Kindly raise an issue here https://developer.microsoft.com/en-us/graph/support so that the API owner can respond to it.

**Comment by davidteijeiro** [comment]
Hello there, I found the solution to this issue in this post: https://www.reddit.com/r/PowerShell/comments/175ol1l/setuserphoto_to_setmguserphotocontent_script/. Basically, the fix is to load the photo into memory first instead of passing the file directly.
For example:
$buffer = [System.IO.File]::ReadAllBytes($foto.Fullpath)
$stream = [System.IO.MemoryStream]::new($buffer)
Set-MgUserPhotoContent -UserId $usuario.Id -InFile dummy.txt -Data $stream -PassThru
I hope this helps.
