### ISSUE TITLE
Connect-MgGraph -Identity fails under an  Azure system-managed identity in 2.9.0 (worked in 2.8.0)

### ISSUE THREAD

**Issue by pbo-top** [microsoftgraph/msgraph-sdk-powershell#2447]
**Describe the bug**
`Connect-MgGraph -Identity` fails in version 2.9.0, when executed under a system-managed identity in a VMSS in Azure. Setup worked in 2.8.0.

**To Reproduce**
We are running a self-hosted Agent in a VMSS controlled by Azure DevOps. The agent is starting from a emphemeral standard Ubuntu2204 image on each build.
The VMSS has a system-managed identity, which has been granted a reader-role in Azure which provides the rights to call the Graph API.
I would assume the setup with the VMSS and DevOps is not relevant for the bug. The end-result of that setup is that we end up having a VM running under a system-managed identity which fails when calling `Connect-MgGraph -Identity`

```
- pwsh: |
    echo $(Build.BuildNumber)
    Install-Module Microsoft.Graph.Applications -RequiredVersion 2.9.0 -Scope CurrentUser -Force -AllowClobber -Verbose
    Install-Module Az.Accounts -RequiredVersion 2.13.2 -Scope CurrentUser -Force -AllowClobber -Verbose
    Install-Module Az.KeyVault -RequiredVersion 5.0.0 -Scope CurrentUser -Force -AllowClobber -Verbose

- task: PowerShell@2
  displayName: "Test connection"
  inputs:
    targetType: 'inline'
    script: |
      Connect-MgGraph -Identity -Debug
    pwsh: true
```

**Expected behavior**
We get a welcome message in "Test connection":
```
Welcome to Microsoft Graph!
Connected via managedidentity access using 97xxxxxx-xxxxx...
```

**Debug Output**
Running with 2.9.0:
```
DEBUG: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://graph.microsoft.com ] ParentRequestId: 
DEBUG: False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.0 Ubuntu 22.04.3 LTS [2023-11-17 08:22:33Z - 61fd041b-3cc9-458d-9a49-228daec45835] MSAL MSAL.NetCore with assembly version '4.56.0.0'. CorrelationId(61fd041b-3cc9-458d-9a49-228daec45835)
DEBUG: False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.0 Ubuntu 22.04.3 LTS [2023-11-17 08:22:33Z - 61fd041b-3cc9-458d-9a49-228daec45835] === AcquireTokenForClientParameters ===
SendX5C: False
ForceRefresh: False

DEBUG: False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.0 Ubuntu 22.04.3 LTS [2023-11-17 08:22:33Z - 61fd041b-3cc9-458d-9a49-228daec45835] 
=== Request Data ===
Authority Provided? - True
Scopes - https://graph.microsoft.com
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenForClient
IsConfidentialClient - True
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 61fd041b-3cc9-458d-9a49-228daec45835
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured: 

DEBUG: False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.0 Ubuntu 22.04.3 LTS [2023-11-17 08:22:33Z - 61fd041b-3cc9-458d-9a49-228daec45835] === Token Acquisition (ClientCredentialRequest) started:
	 Scopes: https://graph.microsoft.com
	Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.0 Ubuntu 22.04.3 LTS [2023-11-17 08:22:33Z - 61fd041b-3cc9-458d-9a49-228daec45835] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.0 Ubuntu 22.04.3 LTS [2023-11-17 08:22:33Z - 61fd041b-3cc9-458d-9a49-228daec45835] [Instance Discovery] Skipping Instance discovery because it is disabled. 
DEBUG: False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.0 Ubuntu 22.04.3 LTS [2023-11-17 08:22:33Z - 61fd041b-3cc9-458d-9a49-228daec45835] [ClientCredentialRequest] Sending Token response to client credential request endpoint ...
DEBUG: Request [3f5c9bb7-4f75-4b4c-bb24-cf4c2fdf1f6b] GET http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=REDACTED
Metadata:REDACTED
x-ms-client-request-id:3f5c9bb7-4f75-4b4c-bb24-cf4c2fdf1f6b
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.10.3 (.NET 8.0.0; Ubuntu 22.04.3 LTS)
client assembly: Azure.Identity
DEBUG: Response [3f5c9bb7-4f75-4b4c-bb24-cf4c2fdf1f6b] 200 OK (00.3s)
Server:IMDS/150.870.65.1103
Date:Fri, 17 Nov 2023 08:22:33 GMT
Content-Type:application/json; charset=utf-8
Content-Length:1774

DEBUG: False MSAL 4.56.0.0 MSAL.NetCore .NET 8.0.0 Ubuntu 22.04.3 LTS [2023-11-17 08:22:34Z - 61fd041b-3cc9-458d-9a49-228daec45835] Exception type: System.IO.FileNotFoundException

   at Azure.Identity.ManagedIdentitySource.HandleResponseAsync(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine& stateMachine)
   at Azure.Identity.ManagedIdentitySource.HandleResponseAsync(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)
   at Azure.Identity.ImdsManagedIdentitySource.<>n__1(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)
   at Azure.Identity.ImdsManagedIdentitySource.HandleResponseAsync(Boolean async, TokenRequestContext context, Response response, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ImdsManagedIdentitySource.AuthenticateAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AuthenticateCoreAsync(Boolean async, TokenRequestContext context, CancellationToken cancellationToken)
   at Azure.Identity.ManagedIdentityClient.AppTokenProviderImpl(AppTokenProviderParameters parameters)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.SendTokenRequestToAppTokenProviderAsync(ILoggerAdapter logger, CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.GetAccessTokenAsync(CancellationToken cancellationToken, ILoggerAdapter logger)
   at Microsoft.Identity.Client.Internal.Requests.ClientCredentialRequest.ExecuteAsync(CancellationToken cancellationToken)
   at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
DEBUG: ManagedIdentityCredential.GetToken was unable to retrieve an access token. Scopes: [ https://graph.microsoft.com ] ParentRequestId:  Exception: Azure.Identity.AuthenticationFailedException (0x80131500): ManagedIdentityCredential authentication failed: Could not load file or assembly 'System.Memory.Data, Version=1.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

See the troubleshooting guide for more information. https://aka.ms/azsdk/net/identity/managedidentitycredential/troubleshoot
 ---> System.IO.FileNotFoundException (0x80070002): Could not load file or assembly 'System.Memory.Data, Version=1.0.2.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file specified.

Connect-MgGraph: /agent/_work/_temp/7c32ed8a-20c4-4eb5-a8fa-69794b4fb57a.ps1:4
Line |
   4 |  Connect-MgGraph -Identity -Debug
     |  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
     | ManagedIdentityCredential authentication failed: Could not load file or
     | assembly 'System.Memory.Data, Version=1.0.2.0, Culture=neutral,
     | PublicKeyToken=cc7b13ffcd2ddd51'. The system cannot find the file
     | specified.  See the troubleshooting guide for more information.
     | https://aka.ms/azsdk/net/identity/managedidentitycredential/troubleshoot
##[debug]Exit code 1 received from tool '/usr/bin/pwsh'
##[debug]STDIO streams have closed for tool '/usr/bin/pwsh'
##[debug]task result: Failed
##[error]PowerShell exited with code '1'.
##[debug]Processed: ##vso[task.issue type=error;]PowerShell exited with code '1'.
##[debug]Processed: ##vso[task.complete result=Failed;]PowerShell exited with code '1'
```

Running with 2.8.0:
```
DEBUG: ManagedIdentityCredential.GetToken invoked. Scopes: [ https://graph.microsoft.com ] ParentRequestId: 
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Ubuntu 22.04.3 LTS [2023-11-17 08:35:47Z - 0e8eb0d7-1051-4484-8615-880381438022] MSAL MSAL.NetCore with assembly version '4.49.1.0'. CorrelationId(0e8eb0d7-1051-4484-8615-880381438022)
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Ubuntu 22.04.3 LTS [2023-11-17 08:35:47Z - 0e8eb0d7-1051-4484-8615-880381438022] === AcquireTokenForClientParameters ===
SendX5C: False
ForceRefresh: False

DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Ubuntu 22.04.3 LTS [2023-11-17 08:35:47Z - 0e8eb0d7-1051-4484-8615-880381438022] 
=== Request Data ===
Authority Provided? - True
Scopes - https://graph.microsoft.com
Extra Query Params Keys (space separated) - 
ApiId - AcquireTokenForClient
IsConfidentialClient - True
SendX5C - False
LoginHint ? False
IsBrokerConfigured - False
HomeAccountId - False
CorrelationId - 0e8eb0d7-1051-4484-8615-880381438022
UserAssertion set: False
LongRunningOboCacheKey set: False
Region configured: 

DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Ubuntu 22.04.3 LTS [2023-11-17 08:35:47Z - 0e8eb0d7-1051-4484-8615-880381438022] === Token Acquisition (ClientCredentialRequest) started:
	 Scopes: https://graph.microsoft.com
	Authority Host: login.microsoftonline.com
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Ubuntu 22.04.3 LTS [2023-11-17 08:35:47Z - 0e8eb0d7-1051-4484-8615-880381438022] [Region discovery] Not using a regional authority. 
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Ubuntu 22.04.3 LTS [2023-11-17 08:35:47Z - 0e8eb0d7-1051-4484-8615-880381438022] [Instance Discovery] Skipping Instance discovery because it is disabled. 
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Ubuntu 22.04.3 LTS [2023-11-17 08:35:47Z - 0e8eb0d7-1051-4484-8615-880381438022] Authority validation enabled? False. 
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Ubuntu 22.04.3 LTS [2023-11-17 08:35:47Z - 0e8eb0d7-1051-4484-8615-880381438022] Authority validation - is known env? True. 
DEBUG: Request [af598dcf-2515-4ea4-a757-4700bc8fd000] GET http://169.254.169.254/metadata/identity/oauth2/token?api-version=2018-02-01&resource=REDACTED
Metadata:REDACTED
x-ms-client-request-id:af598dcf-2515-4ea4-a757-4700bc8fd000
x-ms-return-client-request-id:true
User-Agent:azsdk-net-Identity/1.9.0 (.NET 8.0.0; Ubuntu 22.04.3 LTS)
client assembly: Azure.Identity
DEBUG: Response [af598dcf-2515-4ea4-a757-4700bc8fd000] 200 OK (00.0s)
Server:IMDS/150.870.65.1103
Date:Fri, 17 Nov 2023 08:35:47 GMT
Content-Type:application/json; charset=utf-8
Content-Length:1774

DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Ubuntu 22.04.3 LTS [2023-11-17 08:35:47Z - 0e8eb0d7-1051-4484-8615-880381438022] Checking client info returned from the server..
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Ubuntu 22.04.3 LTS [2023-11-17 08:35:47Z - 0e8eb0d7-1051-4484-8615-880381438022] Saving token response to cache..
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Ubuntu 22.04.3 LTS [2023-11-17 08:35:47Z - 0e8eb0d7-1051-4484-8615-880381438022] [SaveTokenResponseAsync] ID Token not present in response. 
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Ubuntu 22.04.3 LTS [2023-11-17 08:35:47Z - 0e8eb0d7-1051-4484-8615-880381438022] Cannot determine home account id - or id token or no client info and no subject 
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Ubuntu 22.04.3 LTS [2023-11-17 08:35:47Z - 0e8eb0d7-1051-4484-8615-880381438022] [SaveTokenResponseAsync] Saving AT in cache and removing overlapping ATs...
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Ubuntu 22.04.3 LTS [2023-11-17 08:35:47Z - 0e8eb0d7-1051-4484-8615-880381438022] Looking for scopes for the authority in the cache which intersect with https://graph.microsoft.com
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Ubuntu 22.04.3 LTS [2023-11-17 08:35:47Z - 0e8eb0d7-1051-4484-8615-880381438022] Intersecting scope entries count - 0
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Ubuntu 22.04.3 LTS [2023-11-17 08:35:47Z - 0e8eb0d7-1051-4484-8615-880381438022] 
	=== Token Acquisition finished successfully:
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Ubuntu 22.04.3 LTS [2023-11-17 08:35:47Z - 0e8eb0d7-1051-4484-8615-880381438022]  AT expiration time: 11/18/2023 08:22:33 +00:00, scopes: https://graph.microsoft.com. source: IdentityProvider
DEBUG: False MSAL 4.49.1.0 MSAL.NetCore .NET 8.0.0 Ubuntu 22.04.3 LTS [2023-11-17 08:35:47Z - 0e8eb0d7-1051-4484-8615-880381438022] Fetched access token from host login.microsoftonline.com. 
DEBUG: ManagedIdentityCredential.GetToken succeeded. Scopes: [ https://graph.microsoft.com ] ParentRequestId:  ExpiresOn: 2023-11-18T08:22:33.9301106+00:00
Welcome to Microsoft Graph!

Connected via managedidentity access using 97xxxxxx....
Readme: https://aka.ms/graph/sdk/powershell
SDK Docs: https://aka.ms/graph/sdk/powershell/docs
API Docs: https://aka.ms/graph/docs

NOTE: You can use the -NoWelcome parameter to suppress this message.

##[debug]$LASTEXITCODE is not set.
##[debug]Exit code 0 received from tool '/usr/bin/pwsh'
##[debug]STDIO streams have closed for tool '/usr/bin/pwsh'

```

**Module Version**
`Microsoft.Graph.Authentication`

**Environment Data**
```
Image: Ubuntu2204
Powershell: 7.4.0-1.deb
Microsoft.Graph.Applications 2.9.0
```

**Workaround??**
We did stumble upon the fact that installing PS `Az.Accounts` and calling this before the Graph it works in 2.9.0, why this is needed in the new version is not clear, and if it is a requirement then documentation should state that clearly.
```
- task: PowerShell@2
  displayName: "Test connection 2"
  inputs:
    targetType: 'inline'
    script: |
      Connect-AzAccount -Identity
      Connect-MgGraph -Identity -Debug
      Get-Module Microsoft.Graph* | Write-host
    pwsh: true
```

**Comment by timayabi2020** [comment]
Hi @pbo-top this issue was resolved by this https://github.com/microsoftgraph/msgraph-sdk-powershell/pull/2442
Please update to version 2.9.1
<img width="692" alt="image" src="https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/10947120/bcab7fb9-c52c-4025-bc0c-641310811f33">

**Comment by nilsjman** [comment]
This error seems to be back in 2.26.1 but only in PS 7.2. 5.1 works fine.
