### ISSUE TITLE
Microsoft.Graph.Authentication Download Failures

### ISSUE THREAD

**Issue by ThisIsBlame** [microsoftgraph/msgraph-sdk-powershell#2491]
Upon running `Install-Module  Microsoft.Graph -Debug -Force` I receive a failed download of Microsoft.Graph.Authentication. Below is the logs I receive of the failures.

`DEBUG: 00:00:55.8401148    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.PackageManagement.NuGetProvider.NuGetClient.DownloadDataToFileAsync(String fileName, String query, NuGetRequest request, NetworkCredential networkCredential, ProgressTracker progressTracker)
VERBOSE: Retry downloading 'https://www.powershellgallery.com/api/v2/package/Microsoft.Graph.Authentication/2.11.1' for '2' more times
VERBOSE: The SSL connection could not be established, see inner exception.                                              
DEBUG: 00:00:55.9670096    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.PackageManagement.NuGetProvider.NuGetClient.DownloadDataToFileAsync(String fileName, String query, NuGetRequest request, NetworkCredential networkCredential, ProgressTracker progressTracker)
VERBOSE: Retry downloading 'https://www.powershellgallery.com/api/v2/package/Microsoft.Graph.Authentication/2.11.1' for '1' more times
VERBOSE: The SSL connection could not be established, see inner exception.                                              
DEBUG: 00:00:56.0954915    at System.Net.Http.ConnectHelper.EstablishSslConnectionAsync(SslClientAuthenticationOptions sslOptions, HttpRequestMessage request, Boolean async, Stream stream, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
   at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
   at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
   at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
   at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
   at Microsoft.PackageManagement.NuGetProvider.NuGetClient.DownloadDataToFileAsync(String fileName, String query, NuGetRequest request, NetworkCredential networkCredential, ProgressTracker progressTracker)
VERBOSE: Retry downloading 'https://www.powershellgallery.com/api/v2/package/Microsoft.Graph.Authentication/2.11.1' for '0' more times
VERBOSE: Downloading package 'Microsoft.Graph.Authentication' failed, please make sure 'https://www.powershellgallery.com/api/v2/package/Microsoft.Graph.Authentication/2.11.1' is accessable.
WARNING: Source Location 'https://www.powershellgallery.com/api/v2/package/Microsoft.Graph.Authentication/2.11.1' is not valid.`

We get this issue across multiple users, but one specific user is able to get the installation to successfully complete. Please let me know any/all required information

**Comment by timayabi2020** [comment]
Hi @ThisIsBlame please share the output of this command ```Get-ExecutionPolicy -List```

**Comment by ThisIsBlame** [comment]
> Hi @ThisIsBlame please share the output of this command `Get-ExecutionPolicy -List`

Get-ExecutionPolicy -List                 

        Scope ExecutionPolicy
        ----- ---------------
MachinePolicy    Unrestricted
   UserPolicy    Unrestricted
      Process    Unrestricted
  CurrentUser    Unrestricted
 LocalMachine    Unrestricted

**Comment by timayabi2020** [comment]
> > Hi @ThisIsBlame please share the output of this command `Get-ExecutionPolicy -List`
> 
> Get-ExecutionPolicy -List
> 
> ```
>     Scope ExecutionPolicy
>     ----- ---------------
> ```
> 
> MachinePolicy Unrestricted UserPolicy Unrestricted Process Unrestricted CurrentUser Unrestricted LocalMachine Unrestricted

Aha... You should try setting the execution policy to remote signed ```Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser``` and retry the installation again. For more information on the installation prerequisites, refer to this article. https://learn.microsoft.com/en-us/powershell/microsoftgraph/installation?view=graph-powershell-1.0

**Comment by ThisIsBlame** [comment]
`Set-ExecutionPolicy -ExecutionPolicy RemoteSigned -Scope CurrentUser                                                                
Set-ExecutionPolicy: Operation is not supported on this platform.`

I had tried this previously, unfortunately.

**Comment by timayabi2020** [comment]
@ThisIsBlame if all is ok, then I suggest that you close this issue. The execution policy was the only logical explanation to the issue you were facing. Also, you can try setting the policy with admin privileges.
