### ISSUE TITLE
https://graph.microsoft.com/beta/security/auditLog/queries/<Id>/records - Conversion from JSON failed

### ISSUE THREAD

**Issue by Jbmainson** [microsoftgraph/msgraph-sdk-powershell#2689]
### Describe the bug

Can't fetch records found by the audit search : Getting the following error :

~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
Invoke-MgGraphRequest : Conversion from JSON failed with error: After parsing a value an unexpected character was encountered: {. Path 'value[406].administrativeUnits', line 1, position 1027566.
At line:1 char:1
+ Invoke-MgGraphRequest -Uri $Uri
+ CategoryInfo          : InvalidOperation: (:) [Invoke-MgGraphRequest], ArgumentException
+ FullyQualifiedErrorId : NotSpecified,Microsoft.Graph.PowerShell.Authentication.Cmdlets.InvokeMgGraphRequest
~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~

### Expected behavior

Records should be displayed

### How to reproduce

Create new audit logs search and fetch records using : 

$Uri = ("https://graph.microsoft.com/beta/security/auditLog/queries/{0}/records?`$Top=999" -f $AuditLogsSearchId)
Invoke-MgGraphRequest -Uri $Uri

![2024-04-17_14h53_50](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/156928570/971b7c75-9b97-4404-bd7f-e56a298818b6)

### Debug output

<details><summary>Click to expand log</summary>
```

<Log output here>

```
</details>

**Comment by petrhollayms** [comment]
Hi @Jbmainson, 
Can you please try the same request in Graph Explorer to see the data and specifically the attribute mentioned in the log message?

Does the same error happen in v1.0?
Could you also please add info about the SDK version you are using?
Thanks!

**Comment by Jbmainson** [comment]
Graph Explorer returns a result that is malformed (while Powershell simply breaks it) :
![2024-05-21_12h08_13](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/156928570/ee499ca0-87e3-4262-b4cb-0083a1c1d054)


Error is different using 1.0 (as it's not available yet I suppose):
![2024-05-21_12h09_10](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/156928570/88acba25-9ee3-425f-97e3-7afcd9f1edb5)


SDK version:
![2024-05-21_12h11_34](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/156928570/3ba29032-e11d-4e13-8961-a3b6874e8420)

**Comment by Jbmainson** [comment]
> Hi @Jbmainson, Can you please try the same request in Graph Explorer to see the data and specifically the attribute mentioned in the log message?
> 
> Does the same error happen in v1.0? Could you also please add info about the SDK version you are using? Thanks!

Graph Explorer returns a result that is malformed (while Powershell simply breaks it) :
![2024-05-21_12h08_13](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/156928570/ee499ca0-87e3-4262-b4cb-0083a1c1d054)


Error is different using 1.0 (as it's not available yet I suppose):
![2024-05-21_12h09_10](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/156928570/88acba25-9ee3-425f-97e3-7afcd9f1edb5)


SDK version:
![2024-05-21_12h11_34](https://github.com/microsoftgraph/msgraph-sdk-powershell/assets/156928570/3ba29032-e11d-4e13-8961-a3b6874e8420)

**Comment by EmilienCourt** [comment]
Hi,

Just FYI, I think this can be linked to https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2677

**Comment by TyrrellStephen** [comment]
I have encountered the same exception:
`Message        : Conversion from JSON failed with error: After parsing a value an unexpected character was encountered: {. Path 'value[897].administrativeUnits', line 1, position 2089584.
ParamName      :
TargetSite     : System.Object ConvertFromJson(System.String, Boolean, System.Nullable`1[System.Int32], System.Management.Automation.ErrorRecord ByRef)
Data           : {}
InnerException : Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: {. Path 'value[897].administrativeUnits', line 1, position 2089584.
                    at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
                    at Newtonsoft.Json.JsonTextReader.Read()
                    at Newtonsoft.Json.JsonWriter.WriteToken(JsonReader reader, Boolean writeChildren, Boolean writeDateConstructorAsDate, Boolean writeComments)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateJObject(JsonReader reader)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateObject(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.CreateValueInternal(JsonReader reader, Type objectType, JsonContract contract, JsonProperty member, JsonContainerContract containerContract, JsonProperty containerMember, Object
                 existingValue)
                    at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
                    at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
                    at Newtonsoft.Json.JsonConvert.DeserializeObject(String value, Type type, JsonSerializerSettings settings)
                    at Microsoft.Graph.PowerShell.Authentication.Helpers.StringUtil.ConvertFromJson(String jsonString, Boolean returnHashtable, Nullable`1 maxDepth, ErrorRecord& error)
HelpLink       :
Source         : Microsoft.Graph.Authentication
HResult        : -2147024809
StackTrace     :    at Microsoft.Graph.PowerShell.Authentication.Helpers.StringUtil.ConvertFromJson(String jsonString, Boolean returnHashtable, Nullable`1 maxDepth, ErrorRecord& error)
                    at Microsoft.Graph.PowerShell.Authentication.Cmdlets.InvokeMgGraphRequest.ProcessResponseAsync(HttpResponseMessage response)
                    at Microsoft.Graph.PowerShell.Authentication.Cmdlets.InvokeMgGraphRequest.ProcessRecordAsync()`

When downloaded manually via Purview there are around ~66,000 records total.

I get the same results when I use HashTable, PSObject and Json output types. It stops at the same point every time

I also attempted doing the same using but with Invoke-RestMethod but the results from that while seemed to just stop after a similar number of records (~20,500) without any error (evident from StatusCode and ResponseHeader) They contains some records that are in common and others that differ.

**Comment by EmilienCourt** [comment]
Hi @petrhollayms @timayabi2020 

I have put some efforts in debugging this in https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/2677#issuecomment-2200078197

My guess from the stacktrace of @Jbmainson and @TyrrellStephen is that this is related to the "administrativeUnits" parts of the event. Was the event that produced that error in the Yammer Workload ?

**Comment by timayabi2020** [comment]
Closing this since it's a duplicate of #2677. Let's engage on that thread.
