### ISSUE TITLE
Get-MgAuditLogSignIn fails with "Input string was not in a correct format"

### ISSUE THREAD

**Issue by o-l-a-v** [microsoftgraph/msgraph-sdk-powershell#290]
Tested using ```Get-MgAuditLogSignIn``` in ```Microsoft.Graph.Identity.AuditLogs``` version 0.7.0, but could not get it to work.

Environment
```
$PsVersionTable

Name                           Value
----                           -----
PSVersion                      7.0.2
PSEdition                      Core
GitCommitId                    7.0.2
OS                             Microsoft Windows 10.0.19041
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0ÔÇª}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0


Get-Module -Name 'Microsoft.Graph*' | Select-Object -Property 'Name','Version'

Name                               Version
----                               -------
Microsoft.Graph.Authentication     0.7.0
Microsoft.Graph.Identity.AuditLogs 0.7.0
Microsoft.Graph.Users.User         0.7.0
```

I connected as such with a user with GA on given tenant.

```powershell
Import-Module -Name 'Microsoft.Graph.Authentication','Microsoft.Graph.Identity.AuditLogs','Microsoft.Graph.Users.User' -Force
Connect-Graph -Scopes ([string[]]('AuditLog.Read.All','Directory.Read.All','User.Read.All'))
```

```Get-MgUser -All``` seemed to work, after the module asked me again for authentication (bug?).

But ```Get-MgAuditLogSignIn``` I could not get to work. Tried:

```powershell
Get-MgAuditLogSignIn
Get-MgAuditLogSignIn -All
Get-MgAuditLogSignIn -All:$true
```

Got following error every time

```powershell
Get-MgAuditLogSignIn_List: Input string was not in a correct format.
```

With debug enabled I got this info. Which, frankly, is useless in debugging what went wrong. What about exposing headers and URL?

```powershell
DEBUG: CmdletBeginProcessing:
DEBUG: CmdletProcessRecordStart:
DEBUG: CmdletProcessRecordAsyncStart:
DEBUG: CmdletGetPipeline:
DEBUG: CmdletBeforeAPICall:
DEBUG: URLCreated: https://graph.microsoft.com/beta/auditLogs/signIns
DEBUG: RequestCreated: https://graph.microsoft.com/beta/auditLogs/signIns
DEBUG: HeaderParametersAdded: https://graph.microsoft.com/beta/auditLogs/signIns
DEBUG: BeforeCall:
DEBUG: ResponseCreated:
DEBUG: BeforeResponseDispatch:
DEBUG: Finally:
DEBUG: CmdletProcessRecordAsyncEnd:
DEBUG: CmdletException: FormatException - Input string was not in a correct format. :    at System.Number.ThrowOverflowOrFormatException(ParsingStatus status, TypeCode type)
   at System.Double.Parse(String s)
   at Microsoft.Graph.PowerShell.Runtime.Json.JsonNumber.op_Implicit(JsonNumber number)
   at Microsoft.Graph.PowerShell.Models.MicrosoftGraphGeoCoordinates..ctor(JsonObject json)
   at Microsoft.Graph.PowerShell.Models.MicrosoftGraphGeoCoordinates.FromJson(JsonNode node)
   at Microsoft.Graph.PowerShell.Models.MicrosoftGraphSignInLocation..ctor(JsonObject json)
   at Microsoft.Graph.PowerShell.Models.MicrosoftGraphSignInLocation.FromJson(JsonNode node)
   at Microsoft.Graph.PowerShell.Models.MicrosoftGraphSignIn..ctor(JsonObject json)
   at Microsoft.Graph.PowerShell.Models.MicrosoftGraphSignIn.FromJson(JsonNode node)
   at Microsoft.Graph.PowerShell.Models.CollectionOfSignIn.<>c.<.ctor>b__13_1(JsonNode __u)
   at System.Linq.Enumerable.SelectEnumerableIterator`2.ToArray()
   at Microsoft.Graph.PowerShell.Models.CollectionOfSignIn.<>c__DisplayClass13_0.<.ctor>b__0()
   at Microsoft.Graph.PowerShell.Models.CollectionOfSignIn..ctor(JsonObject json)
   at Microsoft.Graph.PowerShell.Models.CollectionOfSignIn.FromJson(JsonNode node)
   at Microsoft.Graph.PowerShell.IdentityAuditLogs.<>c.<AuditLogsListSignIns_Call>b__60_0(Task`1 body)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)
--- End of stack trace from previous location where exception was thrown ---
   at System.Threading.Tasks.Task.ExecuteWithThreadLocal(Task& currentTaskSlot, Thread threadPoolThread)
--- End of stack trace from previous location where exception was thrown ---
   at Microsoft.Graph.PowerShell.Cmdlets.GetMgAuditLogSignIn_List.onOk(HttpResponseMessage responseMessage, Task`1 response)
   at Microsoft.Graph.PowerShell.IdentityAuditLogs.AuditLogsListSignIns_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.IdentityAuditLogs.AuditLogsListSignIns_Call(HttpRequestMessage request, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.IdentityAuditLogs.AuditLogsListSignIns(Nullable`1 Top, Nullable`1 Skip, String Search, String Filter, Nullable`1 Count, String[] Orderby, String[] Select, String[] Expand, Func`3 onOk, Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.Cmdlets.GetMgAuditLogSignIn_List.ProcessRecordAsync()
   at Microsoft.Graph.PowerShell.Cmdlets.GetMgAuditLogSignIn_List.ProcessRecordAsync()
Get-MgAuditLogSignIn_List: Input string was not in a correct format.
DEBUG: CmdletProcessRecordEnd:
DEBUG: CmdletEndProcessing:
``` 
[AB#7422](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/7422)

**Comment by peombwa** [comment]
Judging by the stack trace, this looks like a service issue. Can you share a sanitized fiddler capture of the response? It looks like the service is returning a `GeoCoordinates` that's not of type `double`.

**Comment by peetrike** [comment]
Getting same error with PowerShell 5.1

The only difference is, that between _BeforeResponseDispatch_ and _Finally_ it will output details about response.

The module version is 1.2.0

**Comment by peombwa** [comment]
Can you share a sanitized fiddler capture of the response? It looks like service is the wrong values for GeoCoordinates.

**Comment by o-l-a-v** [comment]
I used either English (Canada) or English (Sweden) on my Windows setup. English (Sweden) has caused problems with other programs earlier.

Try repro it with with language/ culture/ formats set to that?

**Comment by peombwa** [comment]
Thanks @o-l-a-v for the repro steps! I have traced the root cause of the issue to the code generator that we use. The deserializer wasn't performing a culture invariant deserialization of `double` types. 

I've opened an issue in the code generator repo to track this bug - https://github.com/Azure/autorest.powershell/issues/772.
