### ISSUE TITLE
Connect-MgGraph needs to be called inbetween cmdlets on USGov environment

### ISSUE THREAD

**Issue by usodst** [microsoftgraph/msgraph-sdk-powershell#575]
PowerShell version : 5.1
Module: Microsoft.Graph1.4.0

Calling any cmdlet after `Connect-MgGraph -Environment USGov` works, but any cmdlets after the initial cmdlet call will throw the following exception:
![image](https://user-images.githubusercontent.com/48147071/110392267-88a73b00-801d-11eb-91d9-500f42e632ec.png)

if `Connect-MgGraph -Environment USGov` is called again, it will return `Welcome to the Migration Graph!` and allow for one more cmdlet to be called before needing to be called again.
 
[AB#8485](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/8485)

**Comment by peombwa** [comment]
@usodst, does this only happen when calling `Invoke-MgGraph` after `Connect-MgGraph`? Could you try calling a command like `Get-MgUser -Debug` with `-Debug` parameter and share a sanitized debug output.

**Comment by usodst** [comment]
@peombwa, after receiving the output from `Get-MgUser`, it appears that this issue only occurs after `Invoke-GraphRequest` is ran. I was able to run `Get-MgUser` multiple times with no exceptions, however as soon as `Invoke-GraphRequest` was called `Get-MgUser` threw an exception after every run and required `Connect-Graph -Environment USGov -Scopes User.ReadBasic.All` to be called. Here is the ouput from `Get-MgUser -Debug` after `Invoke-GraphRequest` was called.

```
> Get-MgUser -Debug
DEBUG: CmdletBeginProcessing: 

Confirm
Continue with this operation?
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): a
DEBUG: CmdletProcessRecordStart: 
DEBUG: CmdletProcessRecordAsyncStart: 
DEBUG: CmdletGetPipeline: 
DEBUG: CmdletBeforeAPICall: 
DEBUG: URLCreated: https://graph.microsoft.com/v1.0/users
DEBUG: RequestCreated: https://graph.microsoft.com/v1.0/users
DEBUG: HeaderParametersAdded: https://graph.microsoft.com/v1.0/users
DEBUG: GET /v1.0/users HTTP/1.1
HTTP: graph.microsoft.com

DEBUG: BeforeCall: 
DEBUG: CmdletProcessRecordAsyncEnd: 
DEBUG: CmdletException: ArgumentNullException - Value cannot be null.
Parameter name: httpResponse :    at Microsoft.Graph.PowerShell.HttpMessageFormatter..ctor(HttpResponseMessage httpResponse)
   at Microsoft.Graph.PowerShell.Module.<Finally>d__5.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Module.<EventHandler>d__4.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Module.<Signal>d__31.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Cmdlets.GetMgUser_List1.<Microsoft-Graph-PowerShell-Runtime-IEventListener-Signal>d__80.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Users.<UsersUserListUser1_Call>d__1113.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Users.<UsersUserListUser1>d__1111.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Cmdlets.GetMgUser_List1.<ProcessRecordAsync>d__82.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Graph.PowerShell.Cmdlets.GetMgUser_List1.<ProcessRecordAsync>d__82.MoveNext()

Confirm
Value cannot be null.
Parameter name: httpResponse
[Y] Yes  [A] Yes to All  [H] Halt Command  [S] Suspend  [?] Help (default is "Y"): a
Get-MgUser : Value cannot be null.
Parameter name: httpResponse
At line:1 char:1
+ Get-MgUser -Debug
+ ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgUser_List1], ArgumentNullException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgUser_List1
 
DEBUG: CmdletProcessRecordEnd: 
DEBUG: CmdletEndProcessing:
```

**Comment by peombwa** [comment]
Thanks for the logs! This looks like an issue with `Invoke-MgGraphRequest`, let me try to repro it on my end.

**Comment by georgend** [comment]
@usodst Please check if the error still occurs with newer versions of the SDK. Thanks for logs! 👍🏽

**Comment by usodst** [comment]
I no longer have to call `Connect-Graph` between cmdlets, but it is now forcing me to sign in after every single cmdlet. I.e. if I call `Get-MgUser` after signing in, it works as intended. But if I call it again, I am forced to authenticate again.

**Comment by peombwa** [comment]
You shouldn't be re-prompted for auth. Use `Disconnect-MgGraph`, then run `Remove-Item "$env:USERPROFILE\.graph" -Recurse -Force` to delete your token cache. `Connect-MgGraph` will then reconstruct a clean token cache for you on the next run. Chances are that your token cache is in an invalid state from the old versions of the SDK.

Also, we changed the default sign-in behavior in v1.6.0 to a browser pop-up, which should be more reliable than device code.

**Comment by usodst** [comment]
@peombwa After deleting the .graph directory and updating the module to 1.6.0, I can confirm after calling Invoke-GraphRequest I am still prompted to re-enter my credentials after each cmdlet calls while connected to a USGov tenant.

**Comment by peombwa** [comment]
Please upgrade to the latest version of the PowerShell SDK, we've made a lot of improvements as to how tokens are stored across multiple platforms. Please open a new issue if the error persists.
