### ISSUE TITLE
Get-MgAuditLogSignin fails with "Input string was not in a correct format"

### ISSUE THREAD

**Issue by KimmoBergius** [microsoftgraph/msgraph-sdk-powershell#643]
I have a bunch of scripts with some of the Microsoft.Graph command specifically to pull information out of Azure AD. One of these files is using the Get-MgAuditLogSignin cmdlet. When I run this particular script on a Windows 10 machine (tried several), it runs cleanly. When I move the script to run on a Windwos Server 2019 machine, this particular cmdlet sometimes (but not all the time) fails with "Input string was not in a correct format". 

How should I go about this? What information do you need to debug?  
[AB#9186](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/9186)

**Comment by peombwa** [comment]
Can you please share a sanitized debug output of `Get-MgAuditLogSignIn -Debug`. This should output a stack trace of where the error is coming from.

Also, are you using the same tenant when using the cmdlet on both machines?

**Comment by KimmoBergius** [comment]
DEBUG: CmdletBeginProcessing: 
DEBUG: CmdletProcessRecordStart: 
DEBUG: CmdletProcessRecordAsyncStart: 
DEBUG: CmdletGetPipeline: 
DEBUG: CmdletBeforeAPICall: 
DEBUG: URLCreated: https://graph.microsoft.com/v1.0/auditLogs/signIns?$top=100&$filter=AppId eq '8155c0cd-9ed4-4b3c-8911-2564877e8187' and status%2FerrorCode eq 0
DEBUG: RequestCreated: https://graph.microsoft.com/v1.0/auditLogs/signIns?$top=100&$filter=AppId eq '8155c0cd-9ed4-4b3c-8911-2564877e8187' and status%2FerrorCode eq 0
DEBUG: HeaderParametersAdded: https://graph.microsoft.com/v1.0/auditLogs/signIns?$top=100&$filter=AppId eq '8155c0cd-9ed4-4b3c-8911-2564877e8187' and status%2FerrorCode eq 0
DEBUG: GET /v1.0/auditLogs/signIns?$top=100&$filter=AppId%20eq%20%278155c0cd-9ed4-4b3c-8911-2564877e8187%27%20and%20status%2FerrorCode%20eq%200 HTTP/1.1
HTTP: graph.microsoft.com


DEBUG: BeforeCall: 
DEBUG: ResponseCreated: 
DEBUG: BeforeResponseDispatch: 
DEBUG: GET https://graph.microsoft.com/v1.0/auditLogs/signIns?$top=100&$filter=AppId%20eq%20%278155c0cd-9ed4-4b3c-8911-2564877e8187%27%20and%20status%2FerrorCode%20eq%200
HTTP/1.1 200 OK
Transfer-Encoding: chunked
Vary: Accept-Encoding
Strict-Transport-Security: max-age=31536000
request-id: 6ff3ba28-26f7-4e99-8d9e-08378eef7400
client-request-id: 6ff3ba28-26f7-4e99-8d9e-08378eef7400
x-ms-ags-diagnostic: {"ServerInfo":{"DataCenter":"West Europe","Slice":"E","Ring":"5","ScaleUnit":"003","RoleInstance":"AM1PEPF00006B73"}}
OData-Version: 4.0
Date: Mon, 03 May 2021 06:48:45 GMT
Content-Encoding: gzip
Content-Type: application/json; odata.metadata=minimal; odata.streaming=true; IEEE754Compatible=false; charset=utf-8


DEBUG: Finally: 
DEBUG: CmdletProcessRecordAsyncEnd: 
DEBUG: CmdletException: FormatException - Input string was not in a correct format. :    at System.Number.ParseDouble(String value, NumberStyles options, NumberFormatInfo numfmt)
   at Microsoft.Graph.PowerShell.Models.MicrosoftGraphGeoCoordinates..ctor(JsonObject json, HashSet`1 exclusions)
   at Microsoft.Graph.PowerShell.Models.MicrosoftGraphGeoCoordinates.FromJson(JsonNode node)
   at Microsoft.Graph.PowerShell.Models.MicrosoftGraphSignInLocation..ctor(JsonObject json, HashSet`1 exclusions)
   at Microsoft.Graph.PowerShell.Models.MicrosoftGraphSignInLocation.FromJson(JsonNode node)
   at Microsoft.Graph.PowerShell.Models.MicrosoftGraphSignIn..ctor(JsonObject json, HashSet`1 exclusions)
   at Microsoft.Graph.PowerShell.Models.MicrosoftGraphSignIn.FromJson(JsonNode node)
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Linq.Buffer`1..ctor(IEnumerable`1 source)
   at System.Linq.Enumerable.ToArray[TSource](IEnumerable`1 source)
   at Microsoft.Graph.PowerShell.Models.CollectionOfSignIn..ctor(JsonObject json, HashSet`1 exclusions)
   at Microsoft.Graph.PowerShell.Models.CollectionOfSignIn.FromJson(JsonNode node)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Cmdlets.GetMgAuditLogSignIn_List.<onOk>d__81.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Reports.<AuditLogsListSignIns_Call>d__70.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Graph.PowerShell.Reports.<AuditLogsListSignIns_Call>d__70.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Reports.<AuditLogsListSignIns>d__64.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Microsoft.Graph.PowerShell.Cmdlets.GetMgAuditLogSignIn_List.<ProcessRecordAsync>d__78.MoveNext()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at Microsoft.Graph.PowerShell.Cmdlets.GetMgAuditLogSignIn_List.<ProcessRecordAsync>d__78.MoveNext()
Get-MgAuditLogSignIn : Input string was not in a correct format.
At line:1 char:1
+ Get-MgAuditLogSignIn -Filter "AppId eq '8155c0cd-9ed4-4b3c-8911-25648 ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Get-MgAuditLogSignIn_List], FormatException
    + FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgAuditLogSignIn_List
 
DEBUG: CmdletProcessRecordEnd: 
DEBUG: CmdletEndProcessing:

**Comment by KimmoBergius** [comment]
Hi @peombwa - to answer your question: yes I am running the cmdlet against the same tenant on both machines.

**Comment by KimmoBergius** [comment]
Hi @peombwa - just to answer your question regarding the tenant: the answer to that is yes, I am running the script against the same Azure AD tenants on both machines.

**Comment by KimmoBergius** [comment]
Just testing this on Windows Server 2016 - getting the same error on that version as well. Is it possible that this is due to some differences in the .NET versions?

**Comment by KimmoBergius** [comment]
Hi @peombwa - any progress on this?

**Comment by peombwa** [comment]
@KimmoBergius we are tracking a similar issue here - https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/290. The issue seems to be service-related, and it depends on your PC's regional settings. We are actively investigating this, and we will share our findings here #290.

**Comment by peombwa** [comment]
I'll close this a duplicate since everything is being tracked by https://github.com/microsoftgraph/msgraph-sdk-powershell/issues/290.
