### ISSUE TITLE
Does not appear to work in Azure Cloud Shell Docker Container

### ISSUE THREAD

**Issue by JustinGrote** [microsoftgraph/msgraph-sdk-powershell#745]
### Reproduce
`docker run -it mcr.microsoft.com/azure-cloudshell /usr/bin/pwsh`

Get-MGGroup, same result for get-mguser
```
Get-MgGroup_List: Value cannot be null. (Parameter 'httpResponse')
PS /desktop> get-error $error[0]

Exception             :
    Type       : System.ArgumentNullException
    Message    : Value cannot be null. (Parameter 'httpResponse')
    ParamName  : httpResponse
    TargetSite : Void .ctor(System.Net.Http.HttpResponseMessage)
    StackTrace :
   at Microsoft.Graph.PowerShell.HttpMessageFormatter..ctor(HttpResponseMessage httpResponse)
   at Microsoft.Graph.PowerShell.Module.Finally(String id, CancellationToken cancellationToken, Func`1 getEventData,
Func`4 signal)
   at Microsoft.Graph.PowerShell.Module.EventHandler(String id, CancellationToken cancellationToken, Func`1
getEventData, Func`4 signal, InvocationInfo invocationInfo, String parameterSetName, Exception exception)
   at Microsoft.Graph.PowerShell.Module.Signal(String id, CancellationToken token, Func`1 getEventData, Func`4 signal,
InvocationInfo invocationInfo, String parameterSetName, Exception exception)
   at
Microsoft.Graph.PowerShell.Cmdlets.GetMgGroup_List.Microsoft.Graph.PowerShell.Runtime.IEventListener.Signal(String id,
CancellationToken token, Func`1 messageData)
   at Microsoft.Graph.PowerShell.Groups.GroupsGroupListGroup_Call(HttpRequestMessage request, Func`3 onOk, Func`3
onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.Groups.GroupsGroupListGroup(String consistencyLevel, Nullable`1 Top, Nullable`1 Skip,
String Search, String Filter, Nullable`1 Count, String[] Orderby, String[] Select, String[] Expand, Func`3 onOk,
Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.Cmdlets.GetMgGroup_List.ProcessRecordAsync()
   at Microsoft.Graph.PowerShell.Cmdlets.GetMgGroup_List.ProcessRecordAsync()
    Source     : Microsoft.Graph.Groups.private
    HResult    : -2147467261
CategoryInfo          : NotSpecified: (:) [Get-MgGroup_List], ArgumentNullException
FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgGroup_List
InvocationInfo        :
    MyCommand        : Get-MgGroup_List
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 31
    Line             : get-mggroup
    PositionMessage  : At line:1 char:1
                       + get-mggroup
                       + ~~~~~~~~~~~
    InvocationName   : get-mggroup
    CommandOrigin    : Internal
ScriptStackTrace      : at Get-MgGroup<Process>,
/root/.local/share/powershell/Modules/Microsoft.Graph.Groups/1.6.0/exports/v1.0/ProxyCmdletDefinitions.ps1: line 11277
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
``` 
### Reproduce
`docker run -it mcr.microsoft.com/azure-cloudshell /usr/bin/pwsh`

Get-MGGroup, same result for get-mguser
```
Get-MgGroup_List: Value cannot be null. (Parameter 'httpResponse')
PS /desktop> get-error $error[0]

Exception             :
    Type       : System.ArgumentNullException
    Message    : Value cannot be null. (Parameter 'httpResponse')
    ParamName  : httpResponse
    TargetSite : Void .ctor(System.Net.Http.HttpResponseMessage)
    StackTrace :
   at Microsoft.Graph.PowerShell.HttpMessageFormatter..ctor(HttpResponseMessage httpResponse)
   at Microsoft.Graph.PowerShell.Module.Finally(String id, CancellationToken cancellationToken, Func`1 getEventData,
Func`4 signal)
   at Microsoft.Graph.PowerShell.Module.EventHandler(String id, CancellationToken cancellationToken, Func`1
getEventData, Func`4 signal, InvocationInfo invocationInfo, String parameterSetName, Exception exception)
   at Microsoft.Graph.PowerShell.Module.Signal(String id, CancellationToken token, Func`1 getEventData, Func`4 signal,
InvocationInfo invocationInfo, String parameterSetName, Exception exception)
   at
Microsoft.Graph.PowerShell.Cmdlets.GetMgGroup_List.Microsoft.Graph.PowerShell.Runtime.IEventListener.Signal(String id,
CancellationToken token, Func`1 messageData)
   at Microsoft.Graph.PowerShell.Groups.GroupsGroupListGroup_Call(HttpRequestMessage request, Func`3 onOk, Func`3
onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.Groups.GroupsGroupListGroup(String consistencyLevel, Nullable`1 Top, Nullable`1 Skip,
String Search, String Filter, Nullable`1 Count, String[] Orderby, String[] Select, String[] Expand, Func`3 onOk,
Func`3 onDefault, IEventListener eventListener, ISendAsync sender)
   at Microsoft.Graph.PowerShell.Cmdlets.GetMgGroup_List.ProcessRecordAsync()
   at Microsoft.Graph.PowerShell.Cmdlets.GetMgGroup_List.ProcessRecordAsync()
    Source     : Microsoft.Graph.Groups.private
    HResult    : -2147467261
CategoryInfo          : NotSpecified: (:) [Get-MgGroup_List], ArgumentNullException
FullyQualifiedErrorId : Microsoft.Graph.PowerShell.Cmdlets.GetMgGroup_List
InvocationInfo        :
    MyCommand        : Get-MgGroup_List
    ScriptLineNumber : 1
    OffsetInLine     : 1
    HistoryId        : 31
    Line             : get-mggroup
    PositionMessage  : At line:1 char:1
                       + get-mggroup
                       + ~~~~~~~~~~~
    InvocationName   : get-mggroup
    CommandOrigin    : Internal
ScriptStackTrace      : at Get-MgGroup<Process>,
/root/.local/share/powershell/Modules/Microsoft.Graph.Groups/1.6.0/exports/v1.0/ProxyCmdletDefinitions.ps1: line 11277
                        at <ScriptBlock>, <No file>: line 1
PipelineIterationInfo :
```

### Environment

```
Name                           Value
----                           -----
PSVersion                      7.1.3
PSEdition                      Core
GitCommitId                    7.1.3
OS                             Linux 5.4.72-microsoft-standard-WSL2 #1 SMP Wed Oct 28 23:40:43 UTC 2020
Platform                       Unix
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```
Modules
```
PS /usr/cloudshell> gmo microsoft.graph.* -ListAvailable

    Directory: /root/.local/share/powershell/Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Script     1.6.0                 Microsoft.Graph.Authentication      Core,Desk {Connect-MgGraph, Disconnect-MgGraph, G…
Script     1.6.0                 Microsoft.Graph.Groups              Core,Desk {Add-MgGroupFavorite, Add-MgGroupToLife…
Script     1.6.0                 Microsoft.Graph.Users               Core,Desk {Get-MgUser, Get-MgUserCreatedObject, G…
```

[AB#10164](https://microsoftgraph.visualstudio.com/0985d294-5762-4bc2-a565-161ef349ca3e/_workitems/edit/10164)

**Comment by peombwa** [comment]
I can confirm this is indeed a bug with the SDK. As workaround, you can use [Azure Cloud Shell](https://shell.azure.com/) as we resolve this.

**Comment by peombwa** [comment]
The bug seems to be emanating from our auth module when trying to fetch a new token from our authentication providers. See the stack trace below:
``` powershell
PS /usr/cloudshell> try { Get-MgUser -ErrorAction Stop } catch { $_.Exception.InnerException }

TargetSite     : Void WaitOurTurn()
StackTrace     :    at Microsoft.Graph.PowerShell.Authentication.Helpers.CustomAsyncCommandRuntime.WaitOurTurn()
                    at Microsoft.Graph.PowerShell.Authentication.Helpers.CustomAsyncCommandRuntime.WriteObject(Object sendToPipeline)
                    at Microsoft.Graph.PowerShell.Authentication.Helpers.AuthenticationHelpers.<>c.<GetAuthProvider>b__2_1(DeviceCodeResult result)
                    at Microsoft.Identity.Client.Internal.Requests.DeviceCodeRequest.ExecuteAsync(CancellationToken cancellationToken)
                    at Microsoft.Identity.Client.Internal.Requests.RequestBase.RunAsync(CancellationToken cancellationToken)
                    at Microsoft.Identity.Client.ApiConfig.Executors.PublicClientExecutor.ExecuteAsync(AcquireTokenCommonParameters commonParameters, AcquireTokenWithDeviceCodeParameters deviceCodeParameters, CancellationToken cancellationToken)
                    at Microsoft.Graph.Auth.DeviceCodeProvider.GetNewAccessTokenAsync(CancellationToken cancellationToken, AuthenticationProviderOption msalAuthProviderOption)
Message        : Object reference not set to an instance of an object.
Data           : {}
InnerException :
HelpLink       :
Source         : Microsoft.Graph.Authentication
HResult        : -2147467261
```
A fix will be issued in the auth module.
