### ISSUE TITLE
$ParseException/ thrown when using MS Graph SDK cmdlets

### ISSUE THREAD

**Issue by cmeu** [microsoftgraph/msgraph-sdk-powershell#875]
Hello - I am new to the Graph SDK and just completed installation of pwsh 7.1, and the Microsoft.Graph module(s)

After successfully installing with CurrentUser scope (I am in an enrolled domain environment and unable to install for all users in the current context) I am unable to execute these cmdlets with $ParseException/ errors:

```
PowerShell 7.1.4
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS C:\Windows\System32> Get-InstalledModule Microsoft.Graph

Version              Name                                Repository           Description
-------              ----                                ----------           -----------
1.7.0                Microsoft.Graph                     PSGallery            Microsoft Graph PowerShell module

PS C:\Windows\System32> Get-ChildItem 'HKLM:\SOFTWARE\Microsoft\NET Framework Setup\NDP' -Recurse | Get-ItemProperty -Name Version, Release -ErrorAction 0 | where { $_.PSChildName -match '^(?!S)\p{L}'} | select PSChildName, Version, Release | Select -ExpandProperty Version
2.0.50727.4927
3.0.30729.4926
3.0.4506.4926
3.0.6920.4902
3.5.30729.4926
4.8.04084
4.8.04084
4.0.0.0
PS C:\Windows\System32> Connect-MgGraph
$ParseException/   at System.Management.Automation.ScriptBlock.Create(Parser parser, String fileName, String fileContents)
   at System.Management.Automation.ScriptBlock.Create(ExecutionContext context, String script)
   at System.Management.Automation.CommandInvocationIntrinsics.InvokeScript(String script, Boolean useNewScope, PipelineResultTypes writeToPipeline, IList input, Object[] args)
   at System.Management.Automation.CommandInvocationIntrinsics.InvokeScript(String script)
   at Microsoft.Graph.PowerShell.PSCmdletExtensions.RunScript[T](CommandInvocationIntrinsics cii, String script)
   at Microsoft.Graph.PowerShell.PSCmdletExtensions.RunScript[T](PSCmdlet cmdlet, String script)
   at Microsoft.Graph.PowerShell.Authentication.Utilities.Runtime.Cmdlets.GetScriptCmdlet.GetScriptCmdlets(String scriptFolder)
   at Microsoft.Graph.PowerShell.Authentication.Utilities.Runtime.Cmdlets.GetScriptCmdlet.ProcessRecord()
$IncompleteParseException/   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke[T](IEnumerable input, IList`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke[T]()
   at Microsoft.Graph.PowerShell.PSCmdletExtensions.RunScript[T](String script)
   at Microsoft.Graph.PowerShell.Authentication.Utilities.Runtime.Cmdlets.GetModuleCmdlet.GetModuleCmdlets(String modulePath)
   at Microsoft.Graph.PowerShell.Authentication.Utilities.Runtime.Cmdlets.GetModuleCmdlet.ProcessRecord()
Connect-MgGraph: The term 'Connect-MgGraph' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Windows\System32> Connect-Graph
Connect-Graph: The term 'Connect-Graph' is not recognized as a name of a cmdlet, function, script file, or executable program.
Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
PS C:\Windows\System32>
```

I am encountering this on two distinct workstations (both subject to the same GPOs, and both with fresh installations of PowerShell 7 & Microsoft.Graph SDK)

**Comment by peombwa** [comment]
Hi @cmeu,

Could you please share the output of the following for us to try repo this on our end?
#### Environment
- `$PSVersionTable`
- `$host.CurrentCulture`

#### Modules
- `Get-Module microsoft.graph -ListAvailable`

**Comment by cmeu** [comment]
```
PS C:\Users\cmeurer> $PSVersionTable

Name                           Value
----                           -----
PSVersion                      7.1.4
PSEdition                      Core
GitCommitId                    7.1.4
OS                             Microsoft Windows 10.0.19042
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0…}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0

PS C:\Users\cmeurer> $host.CurrentCulture

LCID             Name             DisplayName
----             ----             -----------
1033             en-US            English (United States)

PS C:\Users\cmeurer> Get-Module microsoft.graph -ListAvailable

    Directory: C:\Users\cmeurer\OneDrive - Lowe's Companies Inc\Documents\PowerShell\Modules

ModuleType Version    PreRelease Name                                PSEdition ExportedCommands
---------- -------    ---------- ----                                --------- ----------------
Manifest   1.7.0                 Microsoft.Graph                     Core,Desk
```

**Comment by cmeu** [comment]
In case it helps, I've expanded the compatible versions

```
PS C:\Users\cmeurer> $PSVersionTable.PSCompatibleVersions

Major  Minor  Build  Revision
-----  -----  -----  --------
1      0      -1     -1
2      0      -1     -1
3      0      -1     -1
4      0      -1     -1
5      0      -1     -1
5      1      10032  0
6      0      0      -1
6      1      0      -1
6      2      0      -1
7      0      0      -1
7      1      4      -1
```

**Comment by peombwa** [comment]
Thanks for the outputs. This is a bug with how our code generator parses the module path when importing modules if the path contains special characters such as `'`.

As a workaround, I would suggest installing the module system-wide as we work to fix this bug - `Install-Module Microsoft.Graph -Scope AllUsers`.

Will be fixed by Azure/autorest.powershell#845.
Duplicated of #879.
